### ISSUE TITLE
Recursive restore doesn't work for rails 3

### ISSUE THREAD

**Issue by c0mrade** [rubysherpas/paranoia#100]
I just came across interesting question on SO :

http://stackoverflow.com/questions/21099252/paranoia-gem-restore

And I tried it myself on my machine I get the same results. I use rails version '3.2.14' and have the following version in my Gemfile.lock paranoia (1.3.2), included in the Gemfile like this : gem 'paranoia', '~> 1.0'

**Comment by radar** [comment]
Hi @c0mrade, could you please look at writing a regression test for this within Paranoia?

**Comment by radar** [comment]
Closing due to staleness.
