### ISSUE TITLE
Failing destroy on parent model does not prevent a "very related model" to be destroyed anyway

### ISSUE THREAD

**Issue by plindelauf** [rubysherpas/paranoia#108]
I have a parent model with a "has_many... dependent: :destroy" association with a related child model. Both models have "acts_as_paranoid". When the before_destroy callback fails on the parent model, I would expect the children not to be (soft) destroyed, but they are. 

Here is the paranoia_test.rb with the failing test case for this: https://gist.github.com/plindelauf/8944656

**Comment by radar** [comment]
@plindelauf Can you please submit that test as a PR?

**Comment by radar** [comment]
Thanks. Let's continue the discussion on #110.
