### ISSUE TITLE
Query containing a join of two paranoia models, only applies paranoia to the parent model

### ISSUE THREAD

**Issue by plindelauf** [rubysherpas/paranoia#111]
When both a parent model and a related model have acts_as_paranoia, and I query the parent model with a join statement (e.g. ParentModel.joins(:related_models).where(related_models: { [come criteria] })), the constructed SQL query does contain  "related_models".deleted_at IS NULL, and thus all destroyed related_models are taken into account in the query. 

See pull request for test case.

**Comment by plindelauf** [comment]
Hmmm... sorry... I don't do this a lot. Somehow the commit for this issue got mixed in the pull request for the other issue I reported. Here's the pull request: https://github.com/radar/paranoia/pull/110

**Comment by moxie** [comment]
This issue appears to have been related to a now resolved ActiveRecord issue. https://github.com/rails/rails/issues/9296 - Encountered this today and learned that the fault did not lie with paranoia.

**Comment by radar** [comment]
Thanks @moxie. I'll close this issue now.
