### ISSUE TITLE
how do you   MyModel.really_destroy_all!    ?

### ISSUE THREAD

**Issue by mikeni** [rubysherpas/paranoia#117]
how can i destroy_all and destroy the soft deleted items as well ?

**Comment by mikeni** [comment]
i tried 4 different things to destroy all, including soft deleted items

ShopItem.delete_all # didn't work, since shopitem is scoped
ShopItem.with_deleted.destroy_all # didn't work since destroy is overrided
ShopItem.unscoped.destroy_all # didn't work, not sure how unscoped works
ShopItem.with_deleted.delete_all # worked but using delete

is there something like ShopItem.really_destroy_all!  ?

**Comment by radar** [comment]
@mikeni Did you try `ShopItem.unscoped.delete_all`?

**Comment by ghost** [comment]
@radar really_destroy_all! would be a great feature.  Currently I'm looping through to destroy like: 

```
result do |r|
  r.really_destroy!
end
```

It would be nice to result.really_destroy_all!  The rails source for destroy_all is here: https://github.com/rails/rails/blob/682d7c7035fed76c42ba6fefa38973387e80409e/activerecord/lib/active_record/relation.rb#L364

**Comment by siakaramalegos** [comment]
I don't think that fix actually fixed the issue. Something like `TableName.really_destroy_all!` would be very useful for populating tasks - I don't want to drop the whole database just to destroy the data inside each table, and looping through all records of only Paranoia-enabled tables seems silly too.
