### ISSUE TITLE
About the  has_one association problem

### ISSUE THREAD

**Issue by kai209209** [rubysherpas/paranoia#120]
![catch](https://f.cloud.github.com/assets/5562823/2395250/94ac5f14-a9c6-11e3-8067-5199850fc0f8.png)

My Gemfile file use
gem 'paranoia', :github => 'radar/paranoia', :branch => 'rails4' 

 User model
  has_one :organization, dependent: :destroy
  has_many :activities, dependent: :destroy

Organization model
  belongs_to :user

Activity model
  belongs_to :user

The user has_one organization , and user has_many activities.
Once I restore the user record, execute  "User.restore(10, :recursive => true)", all activities are ok, but the organization still missing. 
Look at the picture, the query :  
SELECT `organizations`.\* FROM `organizations` WHERE `organizations`.`deleted_at` IS NULL AND `organizations`.`user_id` = 10 ORDER BY `organizations`.`id` ASC LIMIT 1  

Why it  found  the record :  'deleted_at' IS NULL
The correct should be "'deleted_at' IS NOT NULL " ,right?
So, is it a bug?

**Comment by kai209209** [comment]
my rails version is  '4.0.2'

**Comment by radar** [comment]
@kai209209 I don't think that it'll fix this particular issue, but you should really upgrade to 4.0.3, since that's the latest release and contains security problems.

**Comment by radar** [comment]
I believe #123 fixes this problem.
