### ISSUE TITLE
overriding getter `def bars` doesn't override `Foo.includes(:bars)`

### ISSUE THREAD

**Issue by brchristian** [rubysherpas/paranoia#130]
I'm overriding the getter method to access soft-deleted associations

```
def bars
Bar.unscoped {super}
end
```

but it doesn't help when I do `Foo.includes(:bars)`. This doesn't give me the soft-deleted stuff, and so I'll get nil exceptions triggered from `foo.bars`. But `foo.reload.bars` works. That seems odd.

Is there a way to do this?

**Comment by radar** [comment]
Please see the ongoing discussion in #109. 

TL;DR: No.
