### ISSUE TITLE
really_destroy! throws error with has_one and belongs_to with dependent flag

### ISSUE THREAD

**Issue by nbwar** [rubysherpas/paranoia#131]
For has_one and belongs_to with dependent: :destroy flag  throws `undefined method 'each' for...`  when calling really_destroy!

**Comment by cre-o** [comment]
Same issue.
And record with `has_one` really destroying after calling #destroy

**Comment by radar** [comment]
Hi @astronz, could you please provide steps to reproduce this issue within a new app?

**Comment by cre-o** [comment]
@radar https://github.com/astronz/paranoia_has_one

Hope it help.

**Comment by radar** [comment]
Thanks for your patch in #151!

**Comment by MarkMurphy** [comment]
Is this fixed?

**Comment by radar** [comment]
@MarkMurphy yes, it looks like it.
