### ISSUE TITLE
Impossibility to declare an association with deleted items

### ISSUE THREAD

**Issue by pierallard** [rubysherpas/paranoia#133]
The gem https://github.com/goncalossilva/acts_as_paranoid owns declares the usage of :with_deleted => true in the association declarations, like this:

``` ruby
belongs_to :parent_including_deleted, :class_name => "Parent", :with_deleted => true
```

This declaration unscope association like with_deleted scope.

I tried several methods to get the same results, but I did not found any solution.
http://stackoverflow.com/questions/23867467/remove-default-scope-in-association/23871202?noredirect=1#comment36745044_23871202

**Comment by donaldpiret** [comment]
Found a way around this by using a purely arel solution. Ugly as hell but it works:

```
class Booking < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :user
  scope :with_deleted_users, -> { joins(arel_table.create_join(User.arel_table,
    arel_table.create_on(arel_table[:user_id].eq(User.arel_table[:id])))) }
end

class User < ActiveRecord::Base
  acts_as_paranoid
  has_many :bookings
end
```
