### ISSUE TITLE
Alias :unscoped to :with_deleted for more meaningful queries?

### ISSUE THREAD

**Issue by efoxepstein** [rubysherpas/paranoia#14]
If we throw `alias :with_deleted :unscoped` in there somewhere, I think

```
Foo.with_deleted.where(...)
```

makes a ton more sense than

```
Foo.unscoped.where(...)
```

because scoping and paranoia are inherently different issues. If you agree, I can submit a pull request.

**Comment by radar** [comment]
I think we discussed this the first time we talked. It should just be a one-line patch of code and then some documentation in the README as well. Please do it.
