### ISSUE TITLE
Before/After really_destroy!

### ISSUE THREAD

**Issue by xtagon** [rubysherpas/paranoia#141]
Hi, I have a case where I need to have a before or after destroy callback, but I only want it to run when the paranoid record is REALLY destroyed. The before_destroy callback runs for both soft deletes and real destroys, which is not what I want.

Any idea how this can be done? Thanks in advance!

**Comment by radar** [comment]
@xtagon You can probably add a `run_callbacks` call to `really_destroy!`, something like `run_callbacks(:really_destroy)` and then define it in the model in the `self.extended` code block, like what's been done with the restore callbacks. A PR to add this to Paranoia would be welcome.
