### ISSUE TITLE
can't have a relationship that isn't "paranoic"

### ISSUE THREAD

**Issue by edgarjs** [rubysherpas/paranoia#142]
I have my model `User` which is paranoic, and it has many products, but my `Product` model isn't paranoic.

And when I do `@user.products`, it generates this query:

```
"SELECT products.* FROM products.deleted_at IS NULL AND products.user_id = $1"
```

As you can see it assumes products table has a `deleted_at` column.

Is there an option to tell the relationship that the related model is not paranoic?

**Comment by radar** [comment]
That shouldn't happen if the `Product` model is not paranoid. Can you reproduce this within a new Rails app? If so, can you make that app available on GitHub?

**Comment by edgarjs** [comment]
I was making the new app from scratch but couldn't replicate. Must be something else in my original app then. I'll dig deeper and let you know if I find something else. Thanks.

**Comment by radar** [comment]
Ok, thanks @edgarjs!
