### ISSUE TITLE
Calling really_destroy! on an ActiveModel raises an exception?

### ISSUE THREAD

**Issue by aryaxt** [rubysherpas/paranoia#145]
I get the following exception when calling really_destroy! on an ActiveModel
ActiveModel is set to acts_as_paranoid

NoMethodError: undefined method `reflections' for #MyActiveRecord:0x00000102793aa8

from /Users/name/.rvm/gems/ruby-2.0.0-p451@company/gems/activemodel-4.1.4/lib/active_model/attribute_methods.rb:435:in `method_missing'

Any idea what's causing this?

**Comment by radar** [comment]
@aryaxt Please show us what version of activerecord you're using.

**Comment by srecnig** [comment]
that should have been fixed in #143. did i miss something in my patch? what version of paranoia are you using?

**Comment by aryaxt** [comment]
Updating my gem fixed the issue. Should have been the first thing to try.

Thanks
