### ISSUE TITLE
Boolean flag_column does not work well

### ISSUE THREAD

**Issue by jiexinhuang** [rubysherpas/paranoia#146]
```
class AddDeletedAtToClients < ActiveRecord::Migration
  def change
    add_column :clients, :deleted_at, :datetime
    add_column :clients, :is_deleted, :boolean, null: false, default: 0
    add_index :clients, [:username, :is_deleted], unique: true
  end
end
```

Use example code in README. If I:
create a new record using
`Client.create(username: 'John')`
Delete it
`Client.first.destroy`
Create another record will success
`Client.create(username: 'John')`

But I will never be able to delete this record unless I change its username
as there is already one record that has `username == 'John'` and `is_deleted == true`

I finally managed to do database unique index by creating partial index like this:
`add_index   :clients, :username, unique: true, where: '"deleted_at" IS NULL'`

**Comment by radar** [comment]
I believe we're working towards a fix for this on #140.

**Comment by EverybodyKurts** [comment]
Has the flag_column option been taken away? It doesn't appear anywhere in the gem anymore.

**Comment by radar** [comment]
@KurtRMueller This was reverted in https://github.com/substantial/paranoia/commit/4aef2da2401bdd1e68036ae57651d041f8b00f5f. Please see the discussion on #140 as to why.
