### ISSUE TITLE
Accessing a value in the options hash returns nil -> No need for options[:val] || nil

### ISSUE THREAD

**Issue by EverybodyKurts** [rubysherpas/paranoia#152]
https://github.com/radar/paranoia/blob/rails4/lib/paranoia.rb#L173

``` ruby
self.paranoia_flag_column = options[:flag_column] || nil
```

Won't the `options` hash already return nil if :flag_column doesn't exist? In other words, there's no need to fall back to a `nil` statement.

``` ruby
[1] pry(main)> options = {}
=> {}
[2] pry(main)> options[:flag_column]
=> nil
```

**Comment by radar** [comment]
Correct. Please submit a patch to fix this.

**Comment by radar** [comment]
@KurtRMueller ping

**Comment by bluej100** [comment]
This line was removed in https://github.com/radar/paranoia/commit/7022080fef75c52141237760ff64c012fa4230ca .

**Comment by radar** [comment]
Thanks @bluej100.
