### ISSUE TITLE
parent soft deletion deleting child records

### ISSUE THREAD

**Issue by ratnakarrao-nyros** [rubysherpas/paranoia#159]
HI ,

When I do soft deletion on parent model , it adds deleted_at perfectly but it destroying child records associated with parent , I am unable to restore child records when I restore parent record. how to do this?

When i perform soft deletion which recursively perform soft deletion on child records, how to do this ?

Can anyone help me asap . thanks

**Comment by styrmis** [comment]
When you restore are you specifying the recursive option?

e.g.

```
YourModel.restore(3, recursive: true)
```

**Comment by radar** [comment]
@ratnakarrao-nyros Please provide exact steps to reproduce.
