### ISSUE TITLE
Soft destroy change update_at attribute

### ISSUE THREAD

**Issue by schovi** [rubysherpas/paranoia#160]
This is more like philosophical question/discussion.
Maybe this problem bothers only me, but i think lifecycle of model should keep `updated_at` unaffected after destroying it. It does not makes sense. You did not update model, you just destroy it and that information is keep in `deleted_at` attribute.

What do you think?

**Comment by radar** [comment]
The state of the model changed, which means that the model has been updated, so `updated_at` should be updated.

**Comment by schovi** [comment]
Yeah, like on destroy you permanently remove db record. 
Oh wait! You don't with Paranoia gem :)
You can keep updated_at same as it was before. That is reason, why i wanted to open discussion.
