### ISSUE TITLE
destroyed? is false after really_destroy!

### ISSUE THREAD

**Issue by kidlab** [rubysherpas/paranoia#182]
I am using paranoia 2.0.2, `destroyed?` returns `false` after calling `really_destroyed!`

``` ruby
class Post < ActiveRecord::Base
  acts_as_paranoid
end

post.really_destroyed!

post.destroyed?
#=> false
```

**Comment by kidlab** [comment]
I figured out the problem, it's because we totally overwrite the `destroyed?` method of ActiveRecord.
I saw in https://github.com/radar/paranoia/blob/rails4/lib/paranoia.rb#L102

**Comment by radar** [comment]
@kidlab Thanks. Could you please submit a patch to fix this issue?

**Comment by kidlab** [comment]
I checked the code on master, it seems to be fixed! We should bump a new version.

**Comment by radar** [comment]
2.0.3 has been released.

**Comment by kidlab** [comment]
Awesome! Thank you.

**Comment by kidlab** [comment]
I found another issue in the new release. I created https://github.com/radar/paranoia/pull/183
