### ISSUE TITLE
Primary key check in model requires ActiveRecord connection to be established

### ISSUE THREAD

**Issue by marektihkan** [rubysherpas/paranoia#186]
When loading model, which have acts_as_paranoid included, it requires ActiveRecord connection to be established. That makes harder to configure application (using database.yml way might have no issues) by loading your classes before configuring environment (environment configuration might also require some classes from load path).

Is it possible to make that requirement skippable by configuration?

**Comment by radar** [comment]
I believe not... I will need to revert that commit and just add a notice to the README about it.

**Comment by jhawthorn** [comment]
I've reverted #178 in 2ee87601e2b1058b00220c95bd1ff96fe005fdc0. I've also added a regression test (c5ca75593f42870f2744aaf86537b03ff7a8c6dc). This should be fixed. I'd like to cut a new gem in a day or two for this fix.

@marektihkan Thanks for the report. Does the current git fix the issue for you?

**Comment by marektihkan** [comment]
Yes, it works now without requiring ActiveRecord connection when loading models.
