### ISSUE TITLE
Doesn't work with inherited_resources

### ISSUE THREAD

**Issue by coneybeare** [rubysherpas/paranoia#19]
When using the popular josevalim gem [inherited_resourses](https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/actions.rb), paranoia breaks down in a spec environment (haven't tested in production yet). It might be because you are both aliasing destroy.

The expected behavior is that the record is not actually destroyed, but the actual behavior is that it is.

**Comment by radar** [comment]
I'd consider this a feature. _snicker_

If you'd like to submit a patch for this I'd be very open to it.

**Comment by chrislwade** [comment]
@coneybeare Unless I'm mistaken the file you reference above relates to controller level functionality and simply defaults a default destroy controller action (which it aliases as destroy!).  paranoia works at the model level and shouldn't interfere with inherited_resources.  I'll see about putting together a sample project that uses both gems and see if I can re-create this issue.  Maybe inherited_resources is doing something with destroy on the model within the spec environment?  I'll see what I can find.
