### ISSUE TITLE
after_really_destroy :some_method Callback?

### ISSUE THREAD

**Issue by yosriady** [rubysherpas/paranoia#191]
Are before/after really_destroy! callbacks supported?

My use case is when we perform a hard deletion, S3 files are removed for real in the after_really_destroy callback. When we perform a soft deletion, the files remain unchanged.

Cheers.

**Comment by taiyop** [comment]
I have a same problem.

**Comment by edygar** [comment]
It was supposed to work https://github.com/radar/paranoia#callbacks

https://github.com/radar/paranoia/blob/rails4/lib/paranoia.rb#L57-L75

But here I got the message:

> undefined method 'after_real_destroy'

**Comment by LaurensN** [comment]
Is this fixed already?

**Comment by yosriady** [comment]
@LaurensN Have you tried `after_real_destroy`?

**Comment by LaurensN** [comment]
Yes, same error as @edygar, the app won't even boot if I add the callback to my paranoia model. The after_restore callback behaves as expected

**Comment by tolhzar** [comment]
It looks after_real_destroy callback exists in branch rails4 only. Can't find that in tag 2.1.3 which should be installed via bundler. Changed Gemfile entry to the following:
`gem "paranoia", git: "https://github.com/radar/paranoia.git", branch: "rails4"`
Everything looks working now

**Comment by radar** [comment]
2.1.4 released.
