### ISSUE TITLE
Release a new version for the rails3 branch to RubyGems

### ISSUE THREAD

**Issue by neerfri** [rubysherpas/paranoia#200]
Hi,

Will it be possible to release a new version to RubyGems?
From what I see the last version was released a year ago and there are quite a few good additions.

Thanks in advance,

**Comment by radar** [comment]
Sure thing @neerfri. I've released 1.3.4. As a reminder, you can also point at a git branch in your Gemfile:

``` ruby
gem 'paranoia', github: 'radar/paranoia', branch: 'rails3'
```

**Comment by neerfri** [comment]
@radar Thanks!

b.t.w, using git with bundler effects bundler's ability to calculate the dependencies and causes a full index download instead of using the metadata API.

**Comment by vitalis** [comment]
@radar can't find 1.3.4 in rubygems

**Comment by radar** [comment]
My bad, @vitalis.

It's there now :)
