### ISSUE TITLE
counter_cache does not decrement when destroying a child record in rails 4.2

### ISSUE THREAD

**Issue by aaronjensen** [rubysherpas/paranoia#202]
Adding items seems to work fine, but destroying them does not.

**Comment by aaronjensen** [comment]
Just found: https://github.com/radar/paranoia/pull/192 I'll try that out.

**Comment by sergey-alekseev** [comment]
#192 is merged. Can you close the issue?

**Comment by aaronjensen** [comment]
Sure, though I wonder if @radar will release a new version w/ the fix?

**Comment by radar** [comment]
2.1.1 is now available on RubyGems. Thanks @aaronjensen and @sergey-alekseev.
