### ISSUE TITLE
Using a sentinel_value: DateTime.new(0) causes a postgres adapter error

### ISSUE THREAD

**Issue by cindyward1** [rubysherpas/paranoia#206]
When I set the acts_as_paranoid sentinel_value to DateTime.new(0) (as suggested in the README) on the Spree::Payee model, I get the following postgres error when calling paginate(@collection) on spree_payees:

PG::DatetimeFieldOverflow: ERROR:  date/time field value out of range: "0000-01-01 00:00:00.000000"
LINE 1: ...pree_payees"  WHERE "spree_payees"."deleted_at" = '0000-01-0...
                                                             ^
: SELECT COUNT(*) FROM "spree_payees"  WHERE "spree_payees"."deleted_at" = '0000-01-01 00:00:00.000000' AND "spree_payees"."deleted_at" IS NULL

I don't think the kaminari gem is the problem since I get the same error in psql when I issue the same SQL command. I've attached a screen shot of the postgres abort. Please note that this error does not occur when using the sqlite3 adapter.

![screen shot 2015-01-29 at 2 29 36 pm](https://cloud.githubusercontent.com/assets/8136992/5969142/c1ff6c7e-a7d4-11e4-8757-22462c27b221.png)

**Comment by jhawthorn** [comment]
Sounds like that's not a valid sentinel value for postgresql. Is there a reason you didn't want to use the default `NULL` sentinel value, I believe that a btree postgresql index will work on those, so there should be no advantage to using `DateTime.new(0)`.

_Doctor, it hurts when I do this.
Don't do that._

Thanks for pointing this out. I think this is bad advice to have in our README, I'll probably remove it and move it to our wiki and mention that it is MySQL specific advice.

**Comment by cindyward1** [comment]
I am using a sentinel value with acts_as_paranoid because I'm scoping on deleted_at in a uniqueness validation, and I read that it's not a good idea to scope on a value that can be nil. I discovered that Datetime.new(1) works fine with postgres so I'm going to use it instead. Thanks for the response.

**Comment by cindyward1** [comment]
Unfortunately, despite what my testing showed, Datetime.new(1) does NOT work in practice. (See attached screen shot.) I am not sure what I am going to use as a sentinel value now.

![screen shot 2015-02-06 at 10 34 29 am](https://cloud.githubusercontent.com/assets/8136992/6085154/1c462c50-adec-11e4-895f-e3e5b495b571.png)

**Comment by radar** [comment]
@cindyward1 I would recommend picking a more recent date. Try `Time.at(0)`

**Comment by jhawthorn** [comment]
@cindyward1 Do you actually experience any problems when using NULL as the sentinel?

I've move the section from the README to the wiki, with my own disclaimer added. https://github.com/radar/paranoia/wiki/Custom-sentinel-values

**Comment by cindyward1** [comment]
Thanks for the response. So far I have not experienced any problems with NULL/nil as the sentinel, and in fact, I had to change back to using NULL/nil since we're importing data that doesn't have the deleted_at sentinel defined. We're only in test mode right now; I will research this further to see if I truly need to use a non-NULL/nil sentinel value. If I do, I think I'll use a valid but impossible date like DateTime.new(1900,1,1) ... Cindy

```
 On Sunday, February 8, 2015 10:08 PM, John Hawthorn <notifications@github.com> wrote:
```

 @cindyward1 Do you actually experience any problems when using NULL as the sentinel?I've removed the advice from the README, and have moved it to the wiki, with my own disclaimer added. https://github.com/radar/paranoia/wiki/Custom-sentinel-values—
