### ISSUE TITLE
"duplicate key value violates unique constraint"

### ISSUE THREAD

**Issue by benwoodward** [rubysherpas/paranoia#208]
#### Error on creating new record that has same id as previously destroyed record

``` ruby
ERROR:  duplicate key value violates unique constraint "index_companies_on_linkedin_id"
DETAIL:  Key (linkedin_id)=(12345678) already exists.
```
#### schema.rb

``` ruby
  create_table "companies", force: true do |t|
    t.integer  "linkedin_id"
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
  end
  add_index "companies", ["linkedin_id"], name: "index_companies_on_linkedin_id", unique: true, using: :btree
```

Is this meant to happen?

**Comment by jhawthorn** [comment]
This is expected. Your unique index has no knowledge that the deleted_at column has a special meaning for us.

Some possible alternatives:
- If you're using postgres :elephant:, a [partial unique index](http://www.postgresql.org/docs/8.0/static/indexes-partial.html) allows you to only index non-deleted values (`WHERE deleted_at IS NOT NULL`).
- You can drop the unique constraint from the index.
- You can add the unique constraint to the pair of `linkedin_id, deleted_at`

Hope this helps.

**Comment by sidevesh** [comment]
@jhawthorn Bit late to this but for ensuring that unique index is only built on non-deleted values, wouldn't it be `WHERE deleted_at IS NULL` ? `WHERE deleted_at IS NOT NULL` seems like will create index on only those which are deleted since deleted_at will be NOT be NULL when a record is deleted.
