### ISSUE TITLE
After destroy, relation remain on memory.

### ISSUE THREAD

**Issue by keepcosmos** [rubysherpas/paranoia#211]
``` ruby
@product.order
```

ex) return order id-1, id-2, id-3

``` ruby
@product.orders.first.destory
@product.orders
```

it returns same as above (id-1, id-2, id-3)
I expect it returns id-2, id-3
Is it correct?

**Comment by radar** [comment]
This is not a problem with Paranoia, but rather a problem with ActiveRecord and how it works. You're calling `destroy` on an instance of `Order` which is different to the instance of `Order` _with the same ID_ within `product.orders`. AR isn't tracking this (it would if it had an identity map), and so it doesn't notice when you delete an order like this.

The solution is to ensure that your association is reloaded:

```
@product.orders.first.destroy
@product.orders.reload
```

And that will return the correct association.

**Comment by keepcosmos** [comment]
Ok, I got it. Thanks @radar
