### ISSUE TITLE
Does it work with Mongoid 4 and does it effectively sign out a use who cancels his account?

### ISSUE THREAD

**Issue by Elyasin** [rubysherpas/paranoia#215]
Hi there, your gem caught my attention. Thanks for your effort guys. I am thinking of using it in my app. However, I wonder whether it is possible to use it with Mongoid 4 and whether a user, who cancels her account, is signed out and prevented from signing in again later.

Regards,
Ely

**Comment by radar** [comment]
No.

This is designed specifically for Active Record. I will not be adding Mongo support ever.
