### ISSUE TITLE
How does the index work

### ISSUE THREAD

**Issue by kapso** [rubysherpas/paranoia#225]
So in the migration, you suggested to create the following index - `add_index :clients, :deleted_at`

But would a `Client.find(1)` query use this index or even primary key index? Don't you need to define a compound index on both `[:id, :deleted_at]` ?

I am using Postgres 9.4, so I would like to think that the database will do merge results after doing scans or those 2 indexes, but I am not sure. Before implementing this gem, I want to make sure that it does not affect query performance. 

Thanks.

**Comment by aselder** [comment]
Client.find(1) will translated to "SELECT \* from clients where deleted_at IS NULL and id = 1"

SQL will use the primary key as it gives a cardinality of 1 and then check this single record to see if it meets additional constraints.

[:id, :deleted_at] is a useless index as the first key restricts the lookup to a single row.

**Comment by kapso** [comment]
@aselder thanks for the explanation. How about in cases where the cardinality is greater than 1, for example the following query. Would you have separate index on `user_id` & `deleted_at` or `[:user_id, :deleted_at]`

`SELECT * from tasks where deleted_at IS NULL and user_id = 5`

**Comment by aselder** [comment]
In those cases you'd want the compound index.

Generally, I just add :deleted_at to the end of all my indexes.

[:user_id, :deleted_at] will function for looks up by user_id and look ups by user_id and deleted_at.
An addition index on :user_id will just waste disk space.

**Comment by kapso** [comment]
@aselder yea that makes sense, thanks again. Found this on how Postgres does index merge in case of multiple indexes.

http://www.postgresql.org/docs/8.3/static/indexes-bitmap-scans.html
