### ISSUE TITLE
acts_as_paranoid class method breaks migrations

### ISSUE THREAD

**Issue by b264** [rubysherpas/paranoia#226]
`Mysql2::Error: Unknown column 'users.deleted_at' in 'where clause': SELECT`users`.* FROM`users`WHERE`users`.`deleted_at`IS NULL`

The only way to make migrations work is to remove the gem.  Any thoughts?

**Comment by b264** [comment]
The `deleted_at` is being referenced before it has been created.

**Comment by b264** [comment]
nasty hack `https://github.com/radar/paranoia/commit/dde7d47b45217333be4831bb0881e76c00f6e43c`

**Comment by radar** [comment]
What is in this migration?

**Comment by b264** [comment]
``` ruby
    User.all.each do |user|
      #user stuff
    end
```

**Comment by radar** [comment]
Why are you referencing a model in a migration? That is bad practice.

**Comment by b264** [comment]
Maybe that's the issue then.  These are legacy migrations.

**Comment by radar** [comment]
Can you rewrite the migration to not refer to the class? I suspect so.

**Comment by b264** [comment]
Yes I rewrote the migrations in SQL and all is well, thank you.

**Comment by radar** [comment]
Great :)

**Comment by liuzhenangel** [comment]
@theB264 

Though it's a bad idea to add AR migrations sentence in migration files, if you had did it, you can solve it dirty and quickly:

``` ruby
# in migration file
User.unscoped.update(balabla...)
```

**Comment by b264** [comment]
@liuzhenangel Oh that's a good idea.  I've rewritten those old migrations and all I've made all since to never touch a child class of `ActiveRecord::Base` and use SQL directly or `ActiveRecord::Migration`.
