### ISSUE TITLE
ActiveRecord::RecordNotDestroyed when dependent associations defined

### ISSUE THREAD

**Issue by dejancancarevic** [rubysherpas/paranoia#240]
Rails 4.1, Paranoia 2.1

A has many B dependent: :destroy
**before_destroy A return false (some validation)**

``` javascript
a.destroy returns 
ActiveRecord::RecordNotDestroyed: ActiveRecord::RecordNotDestroyed
from /usr/lib/ruby/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/persistence.rb:167:in `destroy!'
```

When there is no dependent associations, works fine

**Comment by radar** [comment]
I believe this is intentional behaviour from Active Record. If you think otherwise, please provide steps to reproduce in a new Rails w/ paranoia application.

**Comment by dejancancarevic** [comment]
That's correct, my bad
