### ISSUE TITLE
Access (soft) destroyed record from associated model?

### ISSUE THREAD

**Issue by alejorivera** [rubysherpas/paranoia#248]
Hi there! I've been trying to figure out how to do this. Could someone help me out?

What I want to do, is in essence: `user.destroyed_model.name`

**Comment by radar** [comment]
Spree does this by overriding the association getter: https://github.com/spree/spree/blob/master/core/app/models/spree/variant.rb#L110-L112. I would recommend doing the same thing.

**Comment by alejorivera** [comment]
Awesome, thanks :)
