### ISSUE TITLE
Uniqueness validator does not work well with new paranoia_sentinel_value

### ISSUE THREAD

**Issue by vaharoni** [rubysherpas/paranoia#258]
If I follow the README and do this in my model:

``` ruby
validates_uniqueness_of :email
acts_as_paranoid column: :active, sentinel_value: true
def paranoia_restore_attributes
  {
    deleted_at: nil,
    active: true
  }
end
def paranoia_destroy_attributes
  {
    deleted_at: current_time_from_proper_timezone,
    active: false
  }
end
```

Then running `x.valid?` on that object in console performs the following validation query:

``` sql
SELECT  1 AS one FROM "users" WHERE ("users"."email" = 'email@email.com' AND "users"."active" IS NULL) LIMIT 1
```

which is not desired, as we want `"user"."active" = 't'`.

I noticed in the code the monkey patching of `UniquenessValidator` that looks like this:

``` ruby
if klass.respond_to?(:paranoia_column)
  relation.and(klass.arel_table[klass.paranoia_column].eq(nil))
else
  relation
end
```

Shouldn't `eq(nil)` be changed to `eq(klass.paranoia_sentinel_value)` ?

UPDATE:
I created PR to solve the issue.

**Comment by radar** [comment]
Fixed by #259.
