### ISSUE TITLE
Possible ambiguous column issue for only_deleted

### ISSUE THREAD

**Issue by defconomicron** [rubysherpas/paranoia#26]
Hello.

Suppose there were 2 database tables named alpha and beta and both had a deleted_at column...

One would get an ambiguous column "deleted_at" if the following were attempted:

```
Alpha.joins(:beta).only_deleted
```

Perhaps this:

```
def only_deleted
  unscoped {
    where("deleted_at is not null")
  }
end
```

Should be this:

```
def only_deleted
  unscoped {
    where("#{self.table_name}.deleted_at is not null")
  }
end
```

Or perhaps I am attempting to use this method in a manner that is not intended.

**Comment by radar** [comment]
No, you're right. It should indeed be scoping by the table name. Can you submit a patch for this please?

**Comment by thromera** [comment]
I'm sorry to reopen this issue, but is the problem fixed ? We have from times to times this issue in our project, "ambiguous column active" when using `only_deleted`.
