### ISSUE TITLE
Adds an additional "type" when instantiating STI models

### ISSUE THREAD

**Issue by daino3** [rubysherpas/paranoia#272]
``` ruby
class Firm < ActiveRecord::Base
end

class MemberFirm < Firm
end

class AwesomeFirm < Firm
end

AwesomeFirm.new.type == "[\"AwesomeMember\", \"MemberFirm\"]"
```

I have zero idea why this happens. But sure enough, I remove the gem and it's back to normal.

**Comment by radar** [comment]
What version of rails and paranoia?

**Comment by daino3** [comment]
Sorry, the essentials:
- Rails 4.2.3
- ruby 2.2.2
- paranoia-2.1.3

**Comment by radar** [comment]
I'm unable to reproduce in a new Rails 4.2.4 application.

Please provide an application which reproduces this issue, along with steps to follow to reproduce the issue.

**Comment by daino3** [comment]
Just tried. I can't reproduce outside of our application when pulling out dependencies and bare minimum models. I'm going to close until I can reproduce something for you. Thank you for speedy followup and looking into this. Sorry for not doing my homework before opening an issue :/
