### ISSUE TITLE
Bump version to enable installing latest code from rubygems?

### ISSUE THREAD

**Issue by skarger** [rubysherpas/paranoia#273]
Hello, thanks for this gem.

I noticed that when installing version 2.1.3 from rubygems I get different code than what's on the latest rails4 branch. At the time I'm opening this issue the tip of rails4 is cee809c9065b737627697141a865b156a95ba1c2.

Comparing the current rails4 branch to the commit that bumped lib/paranoia/version.rb to 2.1.3 (ca50876 on Jun 17 2015), there are changes that make a big difference: The newer code provides the ability to  override the paranoia_restore_attributes and paranoia_destroy_attributes methods when using a custom column for the sentinel value.
https://github.com/radar/paranoia/compare/ca50876c9e29d87c555eb2d354ab6378c39a1239...rails4

For me that enhancement is required so that unique indexes work so I installed from github. I was wondering if you could publish a new version (2.2.0?) to make it possible to install that functionality from rubygems. If you like I can submit that as a PR.

**Comment by radar** [comment]
2.1.4 released.
