### ISSUE TITLE
soft-deleted item with dependent destroy soft-deleted associations

### ISSUE THREAD

**Issue by ondrej-zadnik** [rubysherpas/paranoia#275]
Hello,

I have a list of items deleted by paranoia(`Client.only_deleted`) which works pretty nice but if my model have some associations with dependent: destroy which also using paranoia here comes the problem. I'm not able to get these deleted associations cause Rails is getting only associations which are not deleted. Is there any clean solution without adding only_deleted to belongs_to/has_many? Thanks

**Comment by radar** [comment]
Please show some code to help us understand this issue.

**Comment by krainboltgreene** [comment]
@ondulajs Any chance I can get more information on this issue?

**Comment by ondrej-zadnik** [comment]
I have like two models; Client and Message.

``` ruby
class Client < ActiveRecord::Base
  acts_as_paranoid

  has_many :messages, dependent: :destroy


class Message < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :client
```

When I want to destroy a Client, it will delete his messages too. It is ok. But if I want to try to do a loop on Client only_deleted and for each of them show his messages (which are now deleted too), Paranoia will search these messages in active messages.

My models are more complicated, but this is a basic example of what I'm trying to achieve. Thank you.

**Comment by krainboltgreene** [comment]
Thanks so much for the example! Okay, so what you'll need to do is use `#unscoped()` on the messages. Example:

``` ruby
Client.only_deleted.find_each do |client|
  client.messages.unscoped.find_each do |message|

  end
end
```

Let me know if that solves your problem.

The other thing to do is create a custom scope on `Messages` and custom getter on `Client`.

``` ruby
class Client < ActiveRecord::Base
  has_many :messages

  def messages
    deleted? ? super.deleted : super
  end
end

class Message < ActiveRecord::Base
  belongs_to :client

  scope :deleted, -> { where.not(deleted_at: null) }
end
```
