### ISSUE TITLE
Including some built-in RSpec shared examples

### ISSUE THREAD

**Issue by jcf** [rubysherpas/paranoia#28]
Would you be interested in including a shared example to make testing use of `acts_as_paranoid` more simple?

I use the following shared example in my apps to make sure the default scope has been modified as expected.

``` ruby
shared_examples_for 'a paranoid model' do
  describe 'acts_as_paranoid' do
    context 'with the default scope' do
      it 'adds a deleted_at call to all selects' do
        described_class.scoped.where_values_hash.
          should include(deleted_at: nil)
      end
    end

    context 'when unscoped' do
      it 'skips adding the deleted_at condition' do
        described_class.unscoped.where_values_hash.
          should_not have_key(:deleted_at)
      end
    end
  end
end
```

**Comment by Irio** [comment]
:+1:

**Comment by radar** [comment]
@Irio Yes I would be interested in this. Could you please build a PR for this?

**Comment by radar** [comment]
Closing due to staleness.

**Comment by joshuapinter** [comment]
I know you closed this but what's the best method to test that acts_as_paranoid is being included on a model, in Rspec?

`described_class.scoped.where_values_hash` results in `{}`. 

Cheers!
