### ISSUE TITLE
Record not touched on soft destroy

### ISSUE THREAD

**Issue by jeffblake** [rubysherpas/paranoia#296]
I could have sworn this worked as expected (and by paranoia design) that a records `updated_at` attribute gets touched when calling `destroy`. However, thats not happening. I looked at the code, and see a `touch` method call under the `restore` method, but not the `destroy` method. Am I missing something?

**Comment by ccleung** [comment]
I'm noticing this issue too, i think it might have broke with this commit? https://github.com/rubysherpas/paranoia/commit/b2b8d19e62bb633aac24ae5071e81e2230e47396

It updated the updated_at column in 2.1.3, no longer in 2.1.4

**Comment by jeffblake** [comment]
Bump

**Comment by jeffblake** [comment]
Hi Ben,

Hoping we can see this merged in the near future. Thanks :)

**Comment by BenMorganIO** [comment]
@jeffblake alright, I'll take some time to get #311 merged on in tonight.

**Comment by jeffblake** [comment]
@BenMorganIO thanks ben!
