### ISSUE TITLE
Please add Source Code URL to https://rubygems.org/gems/paranoia

### ISSUE THREAD

**Issue by christophermanning** [rubysherpas/paranoia#298]
There is no link to https://github.com/rubysherpas/paranoia on the https://rubygems.org/gems/paranoia page (the homepage links to https://rubygems.org/gems/paranoia). Adding a link would make it easier to get to the github repository from the gem page.

This must be done from the https://rubygems.org/gems/paranoia/edit page by a gem owner.

Thank you.

**Comment by kylefox** [comment]
Big +1 for this, please 😄

**Comment by BenMorganIO** [comment]
![mar-09-2017 18-41-21](https://cloud.githubusercontent.com/assets/3117356/23775718/0d3efe66-04f8-11e7-9ab6-86dff37facb4.gif)
