### ISSUE TITLE
Update callbacks being triggered on destroy

### ISSUE THREAD

**Issue by softwaregravy** [rubysherpas/paranoia#30]
We're seeing an after_update callback getting triggered on a destroy call. (We're sure it's not something else.)

We've looked through the code, and it seems logical and good. 

gems:
paranoia 1.1.0
rails 3.1.6 ( and all the activerecord stuff at the same version)
sqlite3 1.3.5
sqlite3-ruby 1.3.3

**Comment by radar** [comment]
This should be fixed with the latest git release, which uses `update_column` and does not trigger an active record callback.

**Comment by andrezimpel** [comment]
I still got the same problem using 2.1.5.. I got an after_update callback and a after_destroy callback. When destroying the record after_update and after_delete are triggered. Somebody got a hint for me on how to solve that?
