### ISSUE TITLE
Validate uniqueness without deleted items

### ISSUE THREAD

**Issue by anthonator** [rubysherpas/paranoia#31]
There should be a way to ignore items deleted via paranoia when validating the uniqueness of an model.

Currently, if you soft delete an item with a unique constraint on the model you will not be able to recreate a record with the same value.

Unless I'm missing something...

**Comment by kittyflat** [comment]
Having the same issue, current workaround is to use :scope => :deleted_at

**Comment by anthonator** [comment]
Check out https://github.com/anthonator/paranoia_uniqueness_validator

**Comment by mvoto** [comment]
Got the same problem here.
+1 for the scope workaround

**Comment by hottestseason** [comment]
Using `conditions` option might be a good solution

``` ruby
conditions: -> { where(deleted_at: nil)
```

**Comment by mattconnolly** [comment]
The conditions mentioned above appears to work in Rails 4 but not Rails 3.

Adding this class to my Rails 3 project works:

``` ruby
class UniquenessWithoutDeletedValidator < ActiveRecord::Validations::UniquenessValidator
  protected

  def build_relation(klass, table, attribute, value) #:nodoc:
    super.and(table[klass.paranoia_column].eq(nil))
  end
end
```

Then I can do:

``` ruby
class Model
  acts_as_paranoid
  validates :thing_id, uniqueness_without_deleted: {scope: :other_id}
end
```

**Comment by kidlab** [comment]
@anthonator Great plugin, thank you :+1:

**Comment by dhempy** [comment]
@anthonator  's plugin https://github.com/anthonator/paranoia_uniqueness_validator looks like the way to go, for sure.

One wrinkle...it does not yet support non-standard deletion column name. e.g. `acts_as_paranoid column: deleted_date`  In case you're not using deleted_at for your deletion column, here's a close workaround:

    validates :user_name, uniqueness: { scope: :deleted_date }

I think this is not quite perfect, as I believe it would not allow two users with the same user_name to be deleted at the same timestamp. But, that's not a real-world problem for me, and might not be for you.
