### ISSUE TITLE
Question: When to expect 2.2.0 on Rubygems?

### ISSUE THREAD

**Issue by reprah** [rubysherpas/paranoia#313]
I'm interested in using the extra scoping options (`without_default_scope`, etc.) available in paranoia's "core" branch, and see these aren't available in the latest release on Rubygems (2.1.5).

When can we expect a release of 2.2.0, please?

**Comment by connorshea** [comment]
I'm also interested in knowing this for Rails 5 support.

**Comment by westonganger** [comment]
+1 Its time to release a new version

**Comment by BenMorganIO** [comment]
@jhawthorn noticed that you may be able to release a new paranoia gem. Perhaps you may be able to help out with this?

**Comment by connorshea** [comment]
5.0.0.rc1 is out today: https://github.com/rails/rails/releases/tag/v5.0.0.rc1

Wanted to bump this in the hopes of a release?

**Comment by BenMorganIO** [comment]
@connorshea I agree. Its definitely time!!!

**Comment by radar** [comment]
![collaborators 2016-05-12 06-39-19](https://cloud.githubusercontent.com/assets/2687/15195699/4ec18c02-180c-11e6-9154-f8a4735c521c.png)

**Comment by aeons** [comment]
Any update on this?

**Comment by BenMorganIO** [comment]
@aeons yep. Doing some house keeping right now, plucking some low hanging fruit, and then there's a 2.2.0 :tada:

**Comment by connorshea** [comment]
@BenMorganIO 👍

**Comment by ayb** [comment]
+1 trying to install this in Rails 5 and got this error:  `Could not find gem 'paranoia (= 2.2.0.alpha)' in any of the gem sources listed in your Gemfile or available on this machine.`

**Comment by numbcoder** [comment]
When will be 2.2.0 release？

**Comment by rbr** [comment]
@BenMorganIO anything I can help with to speed along the process?

**Comment by connorshea** [comment]
@BenMorganIO Bumping since [Rails 5 has been released today](http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/), thanks for your work on pushing this forward ^_^
