### ISSUE TITLE
'with deleted' doesn't work on Rails tasks

### ISSUE THREAD

**Issue by Sharespot** [rubysherpas/paranoia#317]
Hello! I have the following task to run:

```ruby
require 'net/http'
namespace :seed do

task :set_gid_on_histories => :environment do

    History.all.each do |hist|

        if hist.channel != "REMOTE"
                            if hist.guest
                guest = Guest.find(hist.user_group_id)
                hist.update_attributes(:group_id => guest.group_id)    
            else
                ug = UserGroup.with_deleted.find(hist.user_group_id)
                hist.update_attributes(:group_id => ug.group_id)    
            end     

        end

    end
end

end
```

The problem happens in line                     

ug = UserGroup.with_deleted.find(hist.user_group_id)

What happens is that it's throwing 

ActiveRecord::RecordNotFound: Couldn't find UserGroup with 'id'=71 [WHERE "user_groups"."deleted_at" IS NULL]

just as if there was no 'with deleted' on the command line. 

*_I tried to type the same command on rails console and it worked, i.e. when I run ug = UserGroup.with_deleted.find(71) it works just fine and finds the deleted user.
*_

So it seems that paranoia's 'with_deleted' command is not working on rails tasks... Am I missing something?

**Comment by rbr** [comment]
Which Paranoia version are you using and could you show us your UserGroup model?

**Comment by BenMorganIO** [comment]
It looks more like your `hist.user_group_id` may be `nil` than the `with_deleted` failing.
