### ISSUE TITLE
really_destroy! updates column with datetime even when using sentinel_value

### ISSUE THREAD

**Issue by mhaylock** [rubysherpas/paranoia#326]
Using paranoia 2.1.5, I have a model setup using the `sentinel_value` option, as [documented in the README under "Indexes"](https://github.com/rubysherpas/paranoia#about-indexes), e.g:

``` ruby
add_column :clients, :active, :boolean
add_index :clients, [:group_id, :active], unique: true

class Client < ActiveRecord::Base
  # optionally have paranoia make use of your unique column, so that
  # your lookups will benefit from the unique index
  acts_as_paranoid column: :active, sentinel_value: true

  def paranoia_restore_attributes
    {
      deleted_at: nil,
      active: true
    }
  end

  def paranoia_destroy_attributes
    {
      deleted_at: current_time_from_proper_timezone,
      active: nil
    }
  end
end
```

When calling `really_destroy!` on this model the following warning is generated by Rails (4.2.6):

```
DEPRECATION WARNING: You attempted to assign a value which is not explicitly `true` or `false` (2016-05-17 02:02:23 UTC) to a boolean column. Currently this value casts to `false`. This will change to match Ruby's semantics, and will cast to `true` in Rails 5. If you would like to maintain the current behavior, you should explicitly handle the values you would like cast to `false`.
```

This is because paranoia is writing the current datetime into the paranoia column (`active` in this example), at this line: https://github.com/rubysherpas/paranoia/blob/core/lib/paranoia.rb#L146. I think this should probably use `paranoia_destroy_attributes` instead?

However it's not clear to me why it is even updating the column if it then goes and deletes the row from the database? Why update the column at all?

**Comment by jigneshkhokhani** [comment]
I have same issue with rails 5.0.0.1 and ruby 2.3.1.
Run `@user.really_destroy!` and `@user.destroy` both update deleted_at column.

```
class User
  acts_as_paranoid
end
```

Because of i write `acts_as_paranoid` two time in model and removing one of them solved my problem.
