### ISSUE TITLE
Cannot install paranoia version 2 in rails 5

### ISSUE THREAD

**Issue by saileereddy** [rubysherpas/paranoia#327]
I am trying to install paranoia 2 in rails 5 application but it is giving following issue - 

```
paranoia (~> 2.0) was resolved to 2.0.0, which depends on
      activerecord (~> 4.0)
```

**Comment by Friend-LGA** [comment]
+1

**Comment by abinoam** [comment]
See @lesliev answer in #334 

> gem 'paranoia', :github => 'rubysherpas/paranoia', :branch => 'rails4'
