### ISSUE TITLE
AR callback after_commit :callback, on: :update is being triggered by deleted_at updating

### ISSUE THREAD

**Issue by noahmatisoff** [rubysherpas/paranoia#329]
I have an ActiveRecord `after_commit` callback on one of my models that should only be fired on update.

Example:

``` ruby
class Example
  acts_as_paranoid

  after_commit :run_callback, on: :update

  protected

  def run_callback
    # do stuff
  end
end
```

However, the callback is being fired upon update of the `deleted_at` column on my model, causing other undesired things to occur.  Can code be included in the paranoia codebase to prevent this from occuring, as it is expected for the callback not to fire on update of the `deleted_at` column?

Here is a repository with a fresh Rails app with the paranoia gem to see a reproduction: https://github.com/matisoffn/paranoia-after-commit

Here's also an example reproduction from console:

``` ruby
$ rails c
Running via Spring preloader in process 94034
Loading development environment (Rails 4.2.5)
2.2.1 :001 > Example.create
   (0.2ms)  BEGIN
  SQL (2.0ms)  INSERT INTO `examples` (`created_at`, `updated_at`) VALUES ('2016-06-08 17:15:10', '2016-06-08 17:15:10')
   (1.4ms)  COMMIT
 => #<Example id: 1, name: nil, created_at: "2016-06-08 17:15:10", updated_at: "2016-06-08 17:15:10", deleted_at: nil>
2.2.1 :002 > e = Example.first
  Example Load (2.7ms)  SELECT  `examples`.* FROM `examples` WHERE `examples`.`deleted_at` IS NULL  ORDER BY `examples`.`id` ASC LIMIT 1
 => #<Example id: 1, name: nil, created_at: "2016-06-08 17:15:10", updated_at: "2016-06-08 17:15:10", deleted_at: nil>
2.2.1 :003 > e.name = 'John Doe'
 => "John Doe"
2.2.1 :004 > e.save!
   (0.2ms)  BEGIN
  SQL (3.9ms)  UPDATE `examples` SET `name` = 'John Doe', `updated_at` = '2016-06-08 17:15:22' WHERE `examples`.`id` = 1
   (0.4ms)  COMMIT
run callback
 => true
2.2.1 :005 > e.destroy
   (0.2ms)  BEGIN
  SQL (1.2ms)  UPDATE `examples` SET `examples`.`deleted_at` = '2016-06-08 17:15:33' WHERE `examples`.`id` = 1
   (2.4ms)  COMMIT
run callback
 => #<Example id: 1, name: "John Doe", created_at: "2016-06-08 17:15:10", updated_at: "2016-06-08 17:15:22", deleted_at: "2016-06-08 17:15:33">
```

It is expected that paranoia would override this functionality, preventing `after_commit :method, on: :update` from triggering when `destroy` is called, given that paranoia overrides most ActiveRecord functionality in relation to updating/destroying.

**Comment by rbr** [comment]
Appears to be the same issue as https://github.com/rubysherpas/paranoia/issues/217, which is unfortunately still unresolved.

**Comment by noahmatisoff** [comment]
Darn, ok thanks for pointing that out.
