### ISSUE TITLE
Does not work with Rails 2

### ISSUE THREAD

**Issue by NullVoxPopuli** [rubysherpas/paranoia#33]
```
bundle exec rake gems:install
```

results in

```
gem install paranoia --version ">= 0"
ERROR:  Error installing paranoia:
        activemodel requires activesupport (= 3.2.8)
```

the readme says that `config.gem "paranoia"` should be sufficient, but I guess rails 2 is too old? haha

**Comment by michaek** [comment]
I don't think this is really an issue, as the description says "for Rails 3". Probably using acts_as_paranoid (the original gem) is more appropriate.

**Comment by radar** [comment]
It's not intended to support Rails 2.
