### ISSUE TITLE
Trying to run paranoia in Rails 5

### ISSUE THREAD

**Issue by romalopes** [rubysherpas/paranoia#334]
I tried run paranoia in Rails 5, but when I access the class that I used "acts_as_paranoid", I found the following error:

_**Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)**_

In my Gemfile, I have:

`gem 'rails', '>= 5.0.0.rc1', '< 5.1'
gem "paranoia"`

When I change Gemfile to:
`gem "paranoia", "~> 2.1.5"`

I have the following error:

Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    _**paranoia (~> 2.1.5) was resolved to 2.1.5, which depends on
      activerecord (~> 4.0)

```
rails (< 5.1, >= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
  activerecord (= 5.0.0.rc1)**_
```

I could make paranoia work just making a clone of the project and using the gem: paranoia-2.2.0.alpha.gem

**Comment by lesliev** [comment]
Use the github link in your Gemfile instead:
gem 'paranoia', :github => 'rubysherpas/paranoia', :branch => 'rails4'

The rails4 branch accepts ActiveRecord 5 in its gemspec.

**Comment by ketiko** [comment]
Will there be a gem version bump soon?

**Comment by owenthereal** [comment]
+1 on supporting Rails 5 soon

**Comment by BenMorganIO** [comment]
Going to be doing a Paranoia 2.2.0.pre release :)

**Comment by connorshea** [comment]
@BenMorganIO any news on a 2.2.0 stable release?

**Comment by ghost** [comment]
@rubysherpas @BenMorganIO any news on a 2.2.0 release?

**Comment by tcostam** [comment]
+1 would like a 2.2.0 stable release :)

**Comment by nicwillemse** [comment]
Any news on this  ?
