### ISSUE TITLE
Installing gem breaks ActiveRecord 5 default 'required' behaviour

### ISSUE THREAD

**Issue by lukeredpath** [rubysherpas/paranoia#335]
In Rails 5, associations are required by default.

After installing the paranoia gem, all of my specs that test this behaviour fail. I haven't explicitly required it anywhere (it is required by bundler) and I haven't added `acts_as_paranoid` to any of my models.

I can fix my specs by explicitly adding `required: true` to my associations but this should not be necessary.

**Comment by lukeredpath** [comment]
I'm going to go ahead and close this as this is not a paranoid specific bug - having narrowed it down it seems the cause is the re-opening of the ActiveRecord::Base class at some stage of the Rails initialisation process.

I was able to reproduce the issue simply by re-opening the class in my Rails application.rb:

``` ruby
require 'rails/all'

class ActiveRecord::Base
end

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
```

**Comment by fusion2004** [comment]
It looks like the recommendation from @rafaelfranca is to use `ActiveSupport.on_load(:active_record)`, rather than re-opening the class. In order to implement, we'll need to add `ActiveSupport` as a dependency to `paranoia`.

If that sounds like an acceptable solution to the `paranoia` maintainer(s), I or someone else can make a PR implementing that.

**Comment by BenMorganIO** [comment]
@fusion2004 if you could make a PR, that would be awesome :)

**Comment by fusion2004** [comment]
@BenMorganIO Sure, I will take a crack at it by tomorrow night.

**Comment by connorshea** [comment]
@fusion2004 any updates on this?

**Comment by iaankrynauw** [comment]
For easy access to a solution: 

Moving `Rails.application.config.active_record.belongs_to_required_by_default = true` from `new_framework_defaults.rb` to `application.rb` seems to resolve the problem. 

The above issue referenced says it's an initialization order issue and from what I gather it's not necessarily a paranoia issue.

**Comment by BenMorganIO** [comment]
@iaankrynauw if that's so, would it be OK to close this issue then?

**Comment by BenMorganIO** [comment]
@fusion2004 if you'd still like to submit a patch, that'd be nice too ;)

**Comment by iaankrynauw** [comment]
Hey ok, read a bit further. https://github.com/plataformatec/devise/commit/c2c74b0a39238e7d997486814a1c8f75fdaf276f
`ActiveSupport.on_load(:active_record)`
Looks like this might fix it. I'll test it on Monday.

**Comment by iaankrynauw** [comment]
Looks to me like @fusion2004's `ActiveSupport.on_load(:active_record)` response will solve it. I'll look into it on Monday try and resolve this.

**Comment by BenMorganIO** [comment]
@iaankrynauw Thanks :+1:

**Comment by BenMorganIO** [comment]
See #371
