### ISSUE TITLE
2.2.0 final release

### ISSUE THREAD

**Issue by connorshea** [rubysherpas/paranoia#353]
2.2.0.pre was released in July but no final release has been submitted to RubyGems, are there significant issues that still need to be resolved? Apologies for pestering, we're down to 5 gems blocking our Rails upgrade so I wanted to follow up with each of them.

cc: @BenMorganIO

**Comment by jhawthorn** [comment]
Just released [version 2.2.0](https://rubygems.org/gems/paranoia/versions/2.2.0)

**Comment by connorshea** [comment]
@jhawthorn thank you! ❤️
