### ISSUE TITLE
[Rails 5] only_deleted with cancancan

### ISSUE THREAD

**Issue by flvrone** [rubysherpas/paranoia#356]
Here's the quick example:

```ruby
class CommentsController < ApplicationController
  load_and_authorize_resource
  ...
  def undo_delete
    @comment = Comment.only_deleted.find(params[:id])
    @comment.restore
  end
  ...
end
```

So when `undo_delete` action is fired, the `only_deleted` scope provides the wrong query, here:

```
Started PATCH "/comments/18/undo_delete" for 127.0.0.1 at 2016-09-17 17:51:00 +0300
Processing by CommentsController#undo_delete as JS
  Parameters: {"id"=>"18"}
  User Load (2.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 5], ["LIMIT", 1]]
  Comment Load (1.1ms)  SELECT  "comments".* FROM "comments" WHERE "comments"."deleted_at" IS NULL AND "comments"."id" = $1 LIMIT $2  [["id", 18], ["LIMIT", 1]]
Completed 404 Not Found in 23ms (ActiveRecord: 3.2ms)
```

The trouble is here: _WHERE "comments"."deleted_at" **IS NULL**_

But when I change `load_and_authorize_resource` in my controller to `load_and_authorize_resource except: [:undo_delete]` everything is OK.

I think it shouldn't work like that.

**Comment by filipegorges** [comment]
Hey man, check this: [Rails 5 compatibility between Paranoia and CanCanCan, compromised?](http://stackoverflow.com/questions/39881658/rails-5-compatibility-between-paranoia-and-cancancan-compromised/39903741#39903741)

**Comment by flvrone** [comment]
@filipegorges, you've made an awesome research! :smile: But anyway, you should be aware of these issues: https://github.com/rubysherpas/paranoia/issues/249 , https://github.com/rubysherpas/paranoia/issues/220 . I'm not using this gem anymore because of them, instead I've provided simple solution for my needs like this:
```ruby
class Post < ApplicationRecord
  has_many :comments, -> { without_deleted }
end

class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true

  scope :without_deleted, -> { where(deleted_at: nil) }
  scope :only_deleted, -> { where.not(deleted_at: nil) }

  def restore
    update_attribute(:deleted_at, nil)
  end

  def temp_destroy
    update_attribute(:deleted_at, Time.now)
  end
end

```

Actually I think that you should create a PR with your explanation of cancancan gotcha to close this issue.

**Comment by BenMorganIO** [comment]
@FunkyloverOne since you've found a solution is OK to close this issue?

**Comment by flvrone** [comment]
@BenMorganIO yes, I think so, sorry I haven't done it earlier.
