### ISSUE TITLE
deleted_at in front of the where clause cause performance issue

### ISSUE THREAD

**Issue by ydgiannp** [rubysherpas/paranoia#358]
I see that this gem append the paranoia column as a default_scope. This will cause the paranoia column triggered in front of the where clauses. For example if I want to get `Company.where(id: 508)`

the SQL would be `"SELECT`companies`.* FROM`companies`WHERE`companies`.`deleted_at`IS NULL AND`companies`.`id`= 508"`

this will cause a performance issue because `deleted_at` is put in the beginning of the where clause, not in the end of the where clause. Like this 
`"SELECT`companies`.* FROM`companies`WHERE`companies`.`id`= 508 AND`companies`.`deleted_at`IS NULL"`

Does anybody know how to modify this? It would made a much better performance if it put in the end of the where clauses

**Comment by louim** [comment]
@ydgiannp What makes you think it works that way? SQL queries run trough an optimizer that plans the query before running it. Quick example using PostgreSQL.

With the `deleted_at` first:

``` sql
EXPLAIN SELECT "courses".* FROM "courses" WHERE "courses"."deleted_at" IS NULL AND "courses"."id" = 687
```

```
Index Scan using courses_pkey on courses  (cost=0.28..8.29 rows=1 width=754)
  Index Cond: (id = 687)
  Filter: (deleted_at IS NULL)
```

With the `deleted_at` last:

``` sql
EXPLAIN SELECT "courses".* FROM "courses" WHERE "courses"."id" = 687 AND "courses"."deleted_at" IS NULL
```

```
Index Scan using courses_pkey on courses  (cost=0.28..8.29 rows=1 width=754)
  Index Cond: (id = 687)
  Filter: (deleted_at IS NULL)
```

You get the same query plan regardless of the `where` clause order.

**Comment by jhawthorn** [comment]
The order of `where` conditions will make no difference in performance
