### ISSUE TITLE
Only recover records that have been destroyed through dependent: :destroy callback?

### ISSUE THREAD

**Issue by jawa** [rubysherpas/paranoia#359]
Hi, thanks for a great gem!

I'm sorry if this has been discussed earlier, but I couldn't find anything about it. The feature that I miss the most in this library is to be able to recursively restore only objects that have been destroyed through the `depent: :destroy` callback.

The `acts_as_paranoid` gem seems to have this [feature](https://github.com/ActsAsParanoid/acts_as_paranoid#recovery) and I wonder if there are any reasons for `paranoia` not to have it?

I'd like to help to work on a solution for this if there is interest in it.

**Comment by konto-andrzeja** [comment]
Something like `User.restore(user_id, recursive: true)` doesn't work for you? Or have I misunderstood your question?

**Comment by jawa** [comment]
The use case that I am thinking of is when there is a has many association and a child object is destroyed first, then later the parent object is destroyed (and the rest of the children). When the parent is restored with the children, the child that was first destroyed should not be restored.

**Comment by konto-andrzeja** [comment]
Does [this fork](https://github.com/netguru-hackathon/paranoia) solve your problem?

**Comment by jawa** [comment]
Yes, it seems to do what I was looking for! Nice :-)
