### ISSUE TITLE
destroy is not triggering after_destroy, but really_destroy! does

### ISSUE THREAD

**Issue by tk0221** [rubysherpas/paranoia#362]
In my testing code I use `something.destroy` and it ignore `after_destroy` in something. However, when I use `really_destroy!` it trigger `after_destroy :function`

I use 1.0 version. I don't see any other open issue for this.

**Comment by BenMorganIO** [comment]
If there is an issue, I can't say that it will get fixed anytime soon since you're on a legacy version of paranoia and rails. Sorry :(

If you can confirm that this happens in 2.2, I'll happily take a look at it for you.
