### ISSUE TITLE
cannot load such file -- rspec/expectations paranoia

### ISSUE THREAD

**Issue by Dark-Sun** [rubysherpas/paranoia#363]
I don't have this error in development environment, but it occurs in staging.

The error points to 261 line in paranoia/lib/paranoia.rb

`require 'paranoia/rspec' if defined? RSpec`

I suppose RSpec is somehow defined n my app in staging environment.
The error might be be connected with my environment only, but still this error is strange and I'm not sure why requiring Rspec is needed.

Ruby: 2.3.0
Rails: 5.0.0.1

**Comment by serbiant** [comment]
Hello @Dark-Sun ! Please list your Gemfile here.

**Comment by Dark-Sun** [comment]
source 'https://rubygems.org'
    ruby '2.2.3'
    gem 'rails', '5.0.0.1'
    gem 'jquery-rails'
    gem 'dotenv-rails'
    gem 'pg'
    gem 'puma'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    gem 'sdoc', '~> 0.4.0', group: :doc
    gem 'active_model_serializers' #, '< 0.10.0'
    gem 'devise'
    gem 'cancancan'
    gem 'redis'
    gem 'redis-namespace'
    gem 'redis-rails', '5.0.1'
    gem 'redis-rack-cache', '2.0.0.pre'
    gem 'paperclip', '4.3.0'
    gem 'aws-sdk', '< 2.0'
    gem 'prawn', git: 'https://github.com/stepnivlk/prawn.git'
    gem 'prawn-table'
    gem 'faker'
    gem 'rack-cors'
    gem 'bcrypt'
    gem 'paleta'
    gem 'elasticsearch-model'
    gem 'elasticsearch-rails'
    gem 'dotiw'
    gem 'linkedin-scraper', git: 'https://github.com/stepnivlk/linkedin-scraper.git'
    gem 'papercrop'
    gem 'rmagick'
    gem 'sidekiq'
    gem "sentry-raven"
    gem "librato-rails"
    gem "fast_blank"
    # gem 'euex_templater', git: 'https://github.com/fairpeople/euex_templater.git'
    gem 'rspec_junit_formatter', '0.2.2'
    gem 'prawn-icon'
    gem 'googlestaticmap'
    gem 'joinme2',  git: 'https://github.com/stepnivlk/joinme2'
    gem 'paranoia', '~> 2.2'

    group :development, :test do
      gem 'pry-rails'
      gem 'pry-byebug'
      gem 'capistrano'
      gem 'capistrano-bundler'
      gem 'capistrano-rails'
      gem 'capistrano-rvm'
      gem 'capistrano-passenger'
      gem 'capistrano-ssh-doctor', '~> 1.0'
      gem 'shoulda-matchers'
      gem 'pronto'
      gem 'pronto-rubocop', require: false
    end

    group :development do
      gem 'railroady'
      gem 'awesome_print'
      gem 'bullet'
      gem 'guard-rspec'
      gem 'rubocop'
      gem 'brakeman'
      gem 'rubycritic'
      gem 'web-console', '~> 2.0'
      gem 'spring'
    end

    group :test do
      gem 'pdf-inspector'
      gem 'rspec-rails', '~> 3.0'
      gem 'rspec-nc'
      gem "factory_girl_rails"
      gem 'rspec-collection_matchers'
      gem 'simplecov'
    end

**Comment by serbiant** [comment]
@Dark-Sun hello there.
Take a look at the row
`gem 'rspec_junit_formatter', '0.2.2'`
It's applied for all environments.
If you'd take a look at the code, then you'll notice that this gem requires rspec/core.
https://github.com/sj26/rspec_junit_formatter/blob/master/lib/rspec_junit_formatter.rb#L4
Solution: move that line of including gem to `group :test`.
Hopefully that will help!

**Comment by BenMorganIO** [comment]
Closing since it looks like you just had a gem that shouldn't have been global.
