### ISSUE TITLE
ActiveRecord::FinderMethods::Find does not raise ActiveRecord::RecordNotFound when selecting soft_deleted record

### ISSUE THREAD

**Issue by manuel-burato** [rubysherpas/paranoia#364]
Make Model.find(1) return nil instead of raising an ActiveRecord::RecordNotFound exception when the record with 'id=1' is soft deleted

my specs:
Rails 4.2.7.1
Ruby 2.2.4
paranoia version is 2.2.0

Regards

**Comment by manuel-burato** [comment]
my mistake

**Comment by BenMorganIO** [comment]
Cool. Happy you figured it out :+1:
