### ISSUE TITLE
.restore! does not have any effect

### ISSUE THREAD

**Issue by vbrendel** [rubysherpas/paranoia#37]
With version 1.2.0, calling Thing.only_deleted.find(123456).restore! results in no effect, the SQL that gets run is:

UPDATE "things" SET "deleted_at" = NULL WHERE "things"."deleted_at" IS NULL AND "things"."id" = 123456

It probably has to do with the fixes to the scoping because it worked in previous version.

**Comment by radar** [comment]
The [test for restore](https://github.com/radar/paranoia/blob/cb018cc361e44ed2f0c774749f5e0429f4757a7d/test/paranoia_test.rb#L178-L190) actually tests this exact case. The build passes here.

Do you have some steps to reproduce this issue on a fresh app?

**Comment by vbrendel** [comment]
Hi @radar,

The test passes indeed because destroyed? returns false immediately after calling restore! even though it didn't delete the row from the database. In the test, if you reload the model after doing restore then destroyed? returns true again.

So I would propose to rewrite the test like this:

``` ruby
  def test_restore
    model = ParanoidModel.new
    model.save
    id = model.id
    model.destroy

    assert model.destroyed?

    model = ParanoidModel.only_deleted.find(id)
    model.restore!

    model = ParanoidModel.find(id)

    assert_equal false, model.destroyed?
  end
```

**Comment by radar** [comment]
I can see now.

It doesn't look like anything that we're doing. I think it _might_ be an Active Record bug? I am not sure how to investigate this further.

**Comment by radar** [comment]
I've broken the test for the `restore!` method on purpose now.

**Comment by linjunpop** [comment]
@radar It is a ActiveRecord bug. https://github.com/rails/rails/issues/7357

**Comment by linjunpop** [comment]
A workaround in my application is in an initializer:

``` ruby
module Paranoia
  # override
  def restore!
    true if self.class.unscoped.update_all({deleted_at: nil}, self.class.primary_key => id) > 0
  end
end
```

https://github.com/rails/rails/commit/a3c3cfd

**Comment by radar** [comment]
Thanks for the heads up!

**Comment by linjunpop** [comment]
Rails 3.2.13 should works.
