### ISSUE TITLE
Dependent associations destroyed upon paranoia destruction

### ISSUE THREAD

**Issue by sbonami** [rubysherpas/paranoia#374]
Associations of a paranoia model with the `dependent: :destroy` option are immediately destroyed upon a paranoia destruction, rather than upon the "really_destroy" action.

Is this intended behavior?

**Comment by MaicolBen** [comment]
Yes, it is specified at the start of the readme, it'd be great to have a configuration to disable that

**Comment by sbonami** [comment]
Wow. That's embarrassing! Can't believe I missed that 😂
