### ISSUE TITLE
Repository description is out of date

### ISSUE THREAD

**Issue by benmanns** [rubysherpas/paranoia#376]
The current repo description is `acts_as_paranoid for Rails 3 & 4` but the README states `Paranoia is a re-implementation of acts_as_paranoid for Rails 3/4/5`. Can we update the description to include Rails 5?

**Comment by BenMorganIO** [comment]
Would love to, but I don't actually have that much access.

**Comment by drewish** [comment]
I was also confused by this.

**Comment by BenMorganIO** [comment]
@drewish yes, but I don't have enough access to change it :(

**Comment by SerhiiVynohradov** [comment]
+1.

**Comment by SerhiiVynohradov** [comment]
`really_destroy!` is now `destroy_fully!`

**Comment by sevenseacat** [comment]
Was duplicated in https://github.com/rubysherpas/paranoia/issues/420 and fixed there :)
