### ISSUE TITLE
respond_with @object.destroy raises ActiveRecord::RecordNotFound

### ISSUE THREAD

**Issue by michaelrkn** [rubysherpas/paranoia#38]
In a controller with a destroy method like:

```
def destroy
  respond_with @object.destroy
end
```

calling DELETE /object/:id raises `ActiveRecord::RecordNotFound in ObjectsController#show`.

**Comment by radar** [comment]
Would you be able to write a failing test for this as a patch please?

**Comment by alexisraca** [comment]
plus one to this, i have a default scope that breaks the @variable.destroy from paranoia, is there a way to prevent the default scope while calling destroy on an instance variable?

**Comment by radar** [comment]
@alexisraca I'll make the same request I made 10 months ago: would you be able to write a failing test for this as a patch please?

**Comment by radar** [comment]
Closing due to staleness.
