### ISSUE TITLE
Really delete all paranoia items in a collection

### ISSUE THREAD

**Issue by hieuns** [rubysherpas/paranoia#386]
I have a model, say Author, and it has many Book which `acts_as_paranoid`:

```ruby
class Author < ActiveRecord::Base
  has_many :books
end

class Book < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :author
end
```

If I want to really destroy all books of an author, like `author.books.really_destroy!`, can I do it and which method should I use?

Thanks in advance!

**Comment by BenMorganIO** [comment]
Sounds like you already got a method there: `author.books.really_destroy!`. Are you looking for a single method or do these two suffice?

**Comment by hieuns** [comment]
Thank you for quickly reply.

`author.books.really_destroy!` is just an example. I'm looking for a method that can really destroy all `book`s of `author` in one call, with only one query to database like:
```sql
DELETE FROM books WHERE books.author_id = 1
```
I've try to something like this:
```ruby
author.books.each {|book| book.really_destroy!}
```
but it makes many queries to database (1 query for each `book`)

**Comment by BenMorganIO** [comment]
Oh yeah, Rails would do that. There is a method out there in the Rails-verse that can do it all in one query. Maybe you want `delete_all`: http://api.rubyonrails.org/v4.2/classes/ActiveRecord/Relation.html#method-i-delete_all

**Comment by hieuns** [comment]
Sorry for late reply! But if each `book` has some `has_many` associations and I use `delete_all`, those association will not destroyed as well :(. Does paranoia has a method that can really destroy all item in a collection and all association of each item?

**Comment by BenMorganIO** [comment]
Yep, those associations may not get deleted. You could use referential integrity to get that job done on the DB end.

**Comment by hieuns** [comment]
I got it, thank you!

**Comment by BenMorganIO** [comment]
You're welcome! :D
