### ISSUE TITLE
Problem with Rails 5.1.0.rc1

### ISSUE THREAD

**Issue by igortice** [rubysherpas/paranoia#395]
ArgumentError: wrong number of arguments (given 3, expected 4)

**Comment by BenMorganIO** [comment]
@igortice need more info than that! I have a feeling I know what you're experiencing ;). I'm going to close this as I know we've already resolved this in master.

Can you try using the latest version of Paranoia or the master?

```diff
bundle update paranoia
bin/rspec

# or

# Gemfile
- gem 'paranoia'
+ gem 'paranoia', github: 'rubysherpas/paranoia'

bundle update paranoia
bin/rspec
```

**Comment by igortice** [comment]
thanks, but this comand not work:
gem 'paranoia', github: 'rubysherpas/paranoia'

bundle update paranoia

What worked for me was:
gem 'paranoia', github: 'rubysherpas/paranoia', branch: 'core'

**Comment by BenMorganIO** [comment]
haha yeah, I keep forgetting, this repo is a bit weird in its default branch...
