### ISSUE TITLE
Deleting something later on

### ISSUE THREAD

**Issue by frederikspang** [rubysherpas/paranoia#399]
Would there be an idea in changing the default scopes to use `deleted_at >= NOW()` instead of `IS NULL` and `IS NOT NULL` so that we could implement a method for deleting a record later on? Like deleting a record a month from now; a planned-removal of a kind?

**Comment by vinagrito** [comment]
@frederikspang I think that the idea is to have a value that allows you to get a simple state of the record (on/off) & not save scheduled actions at the record level. Meaning, separating data from logic.

The way I approach your case is by having a background job that fetches deleted records for a time frame of my choice and destroys them e.g: 
```ruby
class CleanupWorker 
  include Sidekiq::Worker

  def perform
     Model.only_deleted.where("deleted_at < ?", 1.month.ago).each(&:really_destroy!)
  end
end
```
