### ISSUE TITLE
Add query to determine of a class is paranoid

### ISSUE THREAD

**Issue by donv** [rubysherpas/paranoia#4]
To be compatible with acts_as_paranoid you need something like this:

class ActiveRecord::Base
  def self.paranoid? ; false ; end
end

module Paranoia
  def self.included(klazz)
    klazz.extend ClassMethods
  end

  def self.paranoid? ; true ; end

  module ClassMethods
    def paranoid? ; true ; end
  end
end

Please add and release a new gem.

**Comment by radar** [comment]
Please consider that people who release gems have lives of their own and may be too busy to do your bidding at the current point.

If you submit a pull request with the code and some simple tests around it I can review, pull, apply it and release a new version.

Thank you.

**Comment by donv** [comment]
Thank you for your quick reply.  I will submit the pull request as soon as I can.

I sincerely appreciate the work you do, and I will do my best to help you.

**Comment by radar** [comment]
Thanks mate! Sorry for the short reply. 1) I just woke up 2) I'm under a lot of pressure to get things done by the end of this week.

Hope to hear back from you shortly.

**Comment by donv** [comment]
Thanks for the quick release.  Issue verified.  Closing.
