### ISSUE TITLE
Bro i'm going to disrupt your life if you push my fucking buttons

### ISSUE THREAD

**Issue by whitmanc** [rubysherpas/paranoia#40]
Bro i'm going to disrupt your life if you push my fucking buttons

**Comment by radar** [comment]
Not an actual issue.

**Comment by parkr** [comment]
You have 3 other issues like this, @whitmanc.

... spam?

**Comment by epochwolf** [comment]
@parkr At the risk of stating the obvious, he's got some kind of personal issue with @radar. He's been harassing some  other people on freenode. I think he's either drunk or high. It's gone from mildly funny to really pathetic in the last hour.

**Comment by ghost** [comment]
@whitmanc quit it man, you're better than this and you're needlessly burning bridges you don't need to. Take a few days off from the computer. Get your mind right and come back. All will be forgiven if you can the crap right now, don't go pushing and doing things you can't come back from. You're better than this!
