### ISSUE TITLE
Do not freeze the deleted object as it breaks interaction with devise

### ISSUE THREAD

**Issue by findchris** [rubysherpas/paranoia#41]
Hi there.

I opened this issue with devise:  https://github.com/plataformatec/devise/issues/2266#issuecomment-13241066

But the issue is actually with paranoia.  In the `delete` method, `freeze` is called on `self`.  This presents a problem as it conflicts with devise (and probably others) in the handling of other object destruction callbacks.  

Do you see any workarounds beyond removing the call to `freeze`?  I was thinking a flag, but that seems messy.

Would appreciate your feedback.  Thanks.

**Comment by avit** [comment]
What's the point of freezing it in the first place? 

It's not frozen when you find something from `Model.with_deleted`, only after calling delete on an existing instance.

It also prevents calling `restore!` without reloading the instance or unfreezing it (e.g. in tests).

**Comment by findchris** [comment]
That is a good point @avit.

@radar Thoughts?

**Comment by martio** [comment]
How to solve this problem? I am using Devise and have the same problem...

**Comment by radar** [comment]
@avit the point of freezing is to match the implementation in AR's own code. AR freezes the instances as well.

I honestly have no attachment to the freezing of the object, so I'm going to remove that now.

**Comment by radar** [comment]
Please try out paranoia master now.

**Comment by martio** [comment]
Great. Thank you! :+1:
