### ISSUE TITLE
Update repo description to include rails 5

### ISSUE THREAD

**Issue by Br3nda** [rubysherpas/paranoia#420]
the first thing most people see when looking at this gem on github is the description at the top:
![image](https://user-images.githubusercontent.com/12266/31847189-ad61c6e8-b674-11e7-99d5-575c69408ff7.png)

but the gem supports rails 5 now. Can you update so it's not leading people wrong.

**Comment by kaoru** [comment]
Please do this, I just spent the afternoon looking at [acts_as_paranoid](https://github.com/ActsAsParanoid/acts_as_paranoid) because I thought it was more up-to-date 😢

**Comment by BenMorganIO** [comment]
I would love to change this, but my permissions aren't high enough to update the text.

**Comment by BenMorganIO** [comment]
cc @jhawthorn @radar. If you guys have enough permissions to make the change, that'd be great!

**Comment by Br3nda** [comment]
@sevenseacat you appear to be the only person left who can do this

**Comment by sevenseacat** [comment]
done :)
