### ISSUE TITLE
AR queries on soft-deleted records trigger after_initialize callbacks

### ISSUE THREAD

**Issue by rlue** [rubysherpas/paranoia#422]
## Problem

Querying a soft-deleted record like so:

```ruby
User.only_deleted.find_by(name: 'Joe Blow')
```

triggers the model's `after_initialize` callbacks. I don't know whether this is intended behavior for paranoia, but it has resulted in unexpected bugs in my application.

Specifically, the `User` model has a callback to ensure that it's always created in tandem with an `Account`:

```ruby
# app/models/user.rb

acts_as_paranoid
has_one :account, dependent: destroy
after_initialize { build_account if account.blank? }
```

This results in divergent behavior:

```ruby
# Normally (i.e., without callbacks)
>> User.only_deleted.find_by(id: 1).account
=> nil

# With after_initialize callback
>> User.only_deleted.find_by(id: 1).account
=> #<Account:0x007fe5d451be38 id: nil, user_id: 1, deleted_at: nil, created_at: nil, updated_at: nil>
```

Thus, if I destroy a user and attempt to restore it, I get the following error:

```ruby
>> user = User.only_deleted.find_by(id: 1)
>> user.restore(recursive: true)
Failure/Error: user.restore(recursive: true) ActiveRecord::ActiveRecordError: cannot update a new record
```

## Workarounds

For anyone who is currently dealing with this problem, the easiest solution is to add a `new_record?` condition to your callback:

```ruby
def set_account
  build_account if new_record? && account.blank?
end
```

What also works is to `#reload` the record you get back from your AR query:

```ruby
=> User.only_deleted.find_by(id: 1).reload.account
=> nil
```

In my case, another solution was to unscope the `#account` getter method, as described in the README:

```ruby
def account
  Account.unscoped { super }
end
```

(This has the obvious disadvantage of unscoping the getter method throughout the entire application, which may not be what you want.)

**Comment by smostovoy** [comment]
you incorrectly understand `after_initialize` callback, what you need is probably `before_create`

**Comment by rlue** [comment]
Thanks, it took me a minute to figure out what you were talking about ;)
