### ISSUE TITLE
Update repo's description

### ISSUE THREAD

**Issue by anmolarora** [rubysherpas/paranoia#445]
README file says it works for Rails 5 but the description says it works only for Rails 3 & 4

**Comment by BenMorganIO** [comment]
Cannot happen as no active contributor has enough access to change the description. Or at least, I cannot.

**Comment by anmolarora** [comment]
Is that so?!
I would like to keep it open with the hope someone might change it in future.

**Comment by Br3nda** [comment]
duplicate of https://github.com/rubysherpas/paranoia/issues/420

**Comment by sevenseacat** [comment]
Fixed :)
