### ISSUE TITLE
unable to use latest version of rails3 branch

### ISSUE THREAD

**Issue by ikbenben** [rubysherpas/paranoia#453]
this is related to issue https://github.com/rubysherpas/paranoia/issues/114

We seem to be experiencing this issue in version 1.3.4 (which is the latest version of the gem for Rails 3). @codeodor mentioned pull requests for both rails 3 and rails 4 but the following does not work:
```
validates_uniqueness_of :platform_id, :scope => [:trainer_id]
```

I've tried to use `validates_uniqueness_of_without_deleted` but that method does not exist:
 ```
undefined methodvalidates_uniqueness_of_without_deleted' for #Class:0x00000005ee9058`
```

I also tried to use `gem "paranoia", github: "rubysherpas/paranoia", branch: "rails3"` as suggested in the README as I noticed the rails3 branch was last updated in Jun 2015 while the v1.3.4 tag was created in Jan 2015. However I'm unable to use this format as the dependancy is in an internal gem and it is not possible to reference a github gem from a gemspec (apparently)
```
s.add_dependency "paranoia", github: "rubysherpas/paranoia", branch: "rails3"
```

so it looks like a new release, v1.3.5 needs to be released with the latest rails3 branch if possible

thanks

**Comment by mathieujobin** [comment]
Rails 3 is no longer supported. the `rails3` branch predates my involvement, I'm not sure in which state it was left in.

surely this issue is outdated too.

I recommend going onto supported version of everything.
