### ISSUE TITLE
Records where deleted_at is nil are still behaving as if they've been deleted

### ISSUE THREAD

**Issue by sstarr** [rubysherpas/paranoia#47]
Hi,

I'm migrating data from a legacy app and some of the models are using the paranoia gem. I've come across some rather weird behaviour which I'm hoping that someone can explain.

The issue is that some records which are (correctly) behaving as if they've been deleted in the legacy app have a `deleted_at` value of `nil`. Here's an example:

```
ruby-1.9.2-p180 :014 > Client.find(93)
ActiveRecord::RecordNotFound: Couldn't find Client with ID=93 [WHERE `clients`.`deleted_at` IS NULL]
ruby-1.9.2-p180 :015 > Client.unscoped.find(93).deleted_at
 => nil 
ruby-1.9.2-p180 :016 > Client.unscoped.find(93).deleted_at.nil?
 => true 
```

This doesn't seem to be affecting the legacy version of the app – everything still appears to be behaving as it should – but it's making it difficult to migrate the data. Because `deleted_at` is sometimes nil, migrated records which have been deleted from the legacy database are showing up in the new version like some kind of zombie uprising.

Edit: Forgot to mention that the legacy app is running version 1.1.0

**Comment by hidde-jan** [comment]
Hi,

Are you using mysql? It sounds like these models have the deleted_at set as 0-0-0 0:0:0, which is NOT NULL, but gets mapped to nil by ActiveRecord.

You could clean up your models by executing the query

```
UPDATE tablename SET deleted_at = NULL WHERE deleted_at = '0-0-0'. 
```

**Comment by sstarr** [comment]
Brilliant, thanks; that was it. I've never seen MySQL do that before!

I managed to get everything back to normal by running this in the console:

``` ruby
Client.unscoped.where(['deleted_at = ?', '0000-00-00 00:00:00']).each { |c| c.update_attribute :deleted_at, c.updated_at }
```

**Comment by radar** [comment]
THanks @hidde-jan :)
