### ISSUE TITLE
Rails 6: after_commit callbacks are not called after destroy on freshly loaded records

### ISSUE THREAD

**Issue by mrhead** [rubysherpas/paranoia#478]
When a freshly loaded record is destroyed, then `after_commit` callbacks are not called. I.e.:

```ruby
user = User.first
user.destroy # after_commit callbacks don't work
```

However if the record is updated after it has been loaded, then everything works as expected.

```ruby
user = User.first
user.touch
user.destroy # after_commit callbacks work
```

It works also on freshly created records therefore the current test suite did not catch this bug.

```ruby
user = User.create!
user.destroy # after_commit callbacks work
```

This happens only on Rails 6.0.0. It works as expected with Rails 5.2.3.

### Steps to reproduce

Run the following ruby script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  # gem "activerecord", "5.2.3" <- this version works
  gem "paranoia"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "paranoia"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.datetime :updated_at
    t.datetime :deleted_at
  end
end

class User < ActiveRecord::Base
  acts_as_paranoid

  after_commit -> { @after_commit_called = true }

  def reset_callback_variables
    @after_commit_called = nil
  end

  def after_commit_callback_called?
    @after_commit_called
  end
end

class BugTest < Minitest::Test
  def setup
    User.create!
    @user = User.first
    refute @user.after_commit_callback_called?
  end

  def test_freshly_loaded_model
    @user.destroy

    assert @user.after_commit_callback_called?
  end

  def test_touched_model
    @user.touch

    @user.destroy

    assert @user.after_commit_callback_called?
  end
end
```

**Comment by rapito** [comment]
If you need a workaround, `after_destroy` works perfectly.

**Comment by hashwin** [comment]
I'm having the same issue, it's the only blocker for me for upgrading to Rails 6.
While ```after_destroy``` is indeed called, it's problematic because I need to enqueue a background job to clean up after destroying, but it's bad practice to enqueue jobs within the db transaction. It should happen ```after_destroy_commit``` which does not fire.

**Comment by mrhead** [comment]
We need to enqueue a job after destroy, too. Although a bit reluctantly, we decided to use `after_destroy` for this and we add a 5 seconds delay during job scheduling to make sure that the DB transaction is committed before the job is executed. It is not ideal, but 🤷‍♂️.

**Comment by mrhead** [comment]
Closing as this was fixed in https://github.com/rubysherpas/paranoia/pull/482. Thanks @hashwin!
