### ISSUE TITLE
"Hard delete" record

### ISSUE THREAD

**Issue by pduersteler** [rubysherpas/paranoia#48]
Let's say, you have an API on which you also sync deleted records (to delete them at the remote location). But after a defined time range, you want to purge those records because they are synced now (means: also deleted at all the remote locations) and you want to reduce the overhead of those deletion checks by definitely removing them from your records.

Is there a possibility to really remove a record from the database? I peeked at the code but could not answer my question.

**Comment by radar** [comment]
Sounds like you want to remove a whole bunch of records at once, which is the perfect use for the `delete_all` method in Rails. I'd recommend using that method to hard-delete the records you wish to delete.
