### ISSUE TITLE
After client.destroy destroyed all dependent: :destroy records

### ISSUE THREAD

**Issue by JARVIS-VOVA** [rubysherpas/paranoia#487]
![image](https://user-images.githubusercontent.com/24324828/75677347-ef1fad80-5c93-11ea-9319-58dd8119dc54.png)
Destroyed all dependent: :destroy records. 
Is it the expected result?

**Comment by JoeHampton** [comment]
Yeah, but that's a feature of Active Record so it shouldn't have anything to do with Paranoia.
