### ISSUE TITLE
uninitialized constant ActiveRecord::Associations::ClassMethods::JoinDependency

### ISSUE THREAD

**Issue by pduersteler** [rubysherpas/paranoia#49]
I just added paranoid to my gemfile and wanted to create a migration.

`paranoid-0.0.7/lib/paranoid/join_association.rb:24:in '<top (required)>': 
 uninitialized constant 
 ActiveRecord::Associations::ClassMethods::JoinDependency (NameError)`

Rails 3.2.12, Ruby 1.9.3-p274

**Comment by radar** [comment]
What is paranoid? This is the _paranoia_ project.

Are you sure you installed the right gem?
