### ISSUE TITLE
Rails 6 support?

### ISSUE THREAD

**Issue by whitewolf92** [rubysherpas/paranoia#504]
Hi,

Will there be support for Rails 6? I keep getting the following error, maybe some methods inside paranoia is deprecated?

`
/Users/cedricloy/.rvm/gems/ruby-2.7.2/gems/activerecord-6.1.0/lib/active_record/scoping/default.rb:92:in 'default_scope': Support for calling #default_scope without a block is removed. For example instead of 'default_scope where(color: 'red')', please use 'default_scope { where(color: 'red') }'. (Alternatively you can just redefine self.default_scope.) (ArgumentError)
       from /Users/test/.rvm/gems/ruby-2.7.2/gems/paranoia-1.2.0/lib/paranoia.rb:49:in `acts_as_paranoid'
`

**Comment by sevenseacat** [comment]
Do you get the same error after upgrading to 2.4.3?

**Comment by whitewolf92** [comment]
Nice, the problem is gone when I upgraded to 2.4.3. Thanks a lot!!
