### ISSUE TITLE
ArgumentError (unknown keyword: :updated_at):

### ISSUE THREAD

**Issue by prativapokhrel** [rubysherpas/paranoia#509]
class User < ActiveRecord::Base
acts_as_paranoid
has_many :school_attendances 
end 

class SchoolAttendance ActiveRecord::Base
 acts_as_paranoid
belongs_to :user 
end 

This is my setup.

Issue: when I try to destroy school_attendance record, I get `ArgumentError (unknown keyword: :updated_at):` in production and staging, but not in development environment.  I don't know how should I debug it and what's this issue. Could please someone help me?

**Comment by andrehjr** [comment]
@prativapokhrel by any chance are you using newrelic_rpm? I got this very same error when using an outdated newrelic_rpm version with Ruby 2.7+. If that's the case, the issue is not related to paranoia. 

If you can provide a backtrace of that error that would be helpful.

**Comment by mathieujobin** [comment]
please reopen if this is still a problem and you can answer the question
