### ISSUE TITLE
2.5.0 missing from Changelog

### ISSUE THREAD

**Issue by nertzy** [rubysherpas/paranoia#520]
There isn't an entry for 2.5.0 in the Changelog.

Is there anything we should know about this version?

Thanks!

**Comment by magni-** [comment]
https://github.com/rubysherpas/paranoia/compare/2.4.3...core

Looks like the changes are:
- dropping support for Ruby < 2.5 and Rails < 5.1
- adding support for Rails 7
- (internal) switching from Travis CI to GitHub for the gem's CI/CD

**Comment by mathieujobin** [comment]
Anyone would like to open a PR with to update the changelog with relevant change respecting the existing format?

**Comment by magni-** [comment]
@mathieujobin done in ☝🏼
