### ISSUE TITLE
Is not v2.5.1 published yet?

### ISSUE THREAD

**Issue by mishina2228** [rubysherpas/paranoia#527]
Currently, v2.5.1 is available on [the release page](https://github.com/rubysherpas/paranoia/releases/tag/v2.5.1), but not in [rubygems.org](https://rubygems.org/gems/paranoia) yet.

**Comment by mathieujobin** [comment]
I was given access to GitHub, but not to push to rubygems yet.
Otherwise, I could push them.

cc: @radar

**Comment by radar** [comment]
> Adding mathieujobin: Owner could not be found.

@mathieujobin Send me your RubyGems username/email address here and I will add you.

**Comment by radar** [comment]
2.5.1 has now been pushed to RubyGems. Apologies for the delay.

**Comment by mathieujobin** [comment]
https://rubygems.org/profiles/mathieu

Thanks @radar

**Comment by radar** [comment]
(Check your email)

```
mathieu was added as an unconfirmed owner. Ownership access will be enabled after the user clicks on the confirmation mail sent to their email.

Owners for gem: paranoia
- ryanbigg
- jhawthorn
- BenMorganIO
- sevenseacat
- ```
-

**Comment by mathieujobin** [comment]
Thanks, I'll update the change log for v2.5.2 and push it later today...

**Comment by mathieujobin** [comment]
v2.5.2 released as well 
## 2.5.2

* [#526](https://github.com/rubysherpas/paranoia/pull/526) Do not include tests files in packaged gem

  [Jason Fleetwood-Boldt](https://github.com/jasonfb)
* [#492](https://github.com/rubysherpas/paranoia/pull/492) Warn if acts_as_paranoid is called more than once on the same model

  [Ignatius Reza](https://github.com/ignatiusreza)

**Comment by mishina2228** [comment]
@mathieujobin @radar  Thank you!
