### ISSUE TITLE
New "deletion_time" does not work with sentinel_value

### ISSUE THREAD

**Issue by sherif-nedap** [rubysherpas/paranoia#530]
https://github.com/rubysherpas/paranoia/pull/481

if you use a sentinel_value that uses a boolean value instead of timestamp

**Comment by mathieujobin** [comment]
would you be able to write a test that reproduce this issue please?

**Comment by sherif-nedap** [comment]
@mathieujobin  i have created a test for it and discovered where the issue is..

https://github.com/rubysherpas/paranoia/pull/531

**Comment by sherif-nedap** [comment]
https://github.com/rubysherpas/paranoia/pull/531#issuecomment-1075301151

**Comment by mathieujobin** [comment]
thanks for the report and the test

fix pushed in v2.5.3
