### ISSUE TITLE
LoadError: cannot load such file -- rspec/expectations

### ISSUE THREAD

**Issue by sunloverz** [rubysherpas/paranoia#539]
I use the latest paranoia 2.6.1 version, when I deploy using capistrano it raises the following error:

      01 ~/.rvm/bin/rvm ruby-2.7.6 do bundle exec rake db:migrate
      01 rake aborted!
      01 LoadError: cannot load such file -- rspec/expectations
      01 /srv/www/project/shared/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
      01 /srv/www/project/shared/bundle/ruby/2.7.0/gems/paranoia-2.6.1/lib/paranoia/rspec.rb:2:in `<main>'
      01 /srv/www/project/shared/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
      01 /srv/www/project/shared/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
      01 /srv/www/project/shared/bundle/ruby/2.7.0/gems/paranoia-2.6.1/lib/paranoia.rb:317:in `<main>'
      01 /srv/www/project/shared/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
      01 /srv/www/project/shared/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

**Comment by sunloverz** [comment]
@swelther @swelther Could you please have a look?

**Comment by mathieujobin** [comment]
why would rspec/anything be loaded on db:migrate?

seems like something is wrong with your setup... 

could also be a gem in `group :test` and bootsnap cannot find it.

I don't know what else it could be...

**Comment by mathieujobin** [comment]
looks unrelated
