### ISSUE TITLE
Paranoia not compatible with Rails 3.0.x

### ISSUE THREAD

**Issue by pcmantz** [rubysherpas/paranoia#54]
In particular, the `default_scoped` attribute appears to have been introduced in Rails 3.1, and is not present in Rails 3.0.20, the latest release.

As far as I know right now, this may only affect the `only_deleted` and `with_deleted` methods that are added onto paranoid models.

**Comment by radar** [comment]
I choose not to support Rails 3.0.

**Comment by pcmantz** [comment]
If this is the case, could you please update the documentation and the gemspec's requirements to reflect this?

I have been using paranoia 1.1.0 with Rails 3.0 with no problems yet, and it would help other people who are upgrading their applications.

**Comment by radar** [comment]
Updated the gemspec to only support > Rails 3.1
