### ISSUE TITLE
`destroy` doesn't work with the new version of Rails 7.0.6

### ISSUE THREAD

**Issue by VitaliSakolski** [rubysherpas/paranoia#544]
When I tried to upgrade to the latest version of Rails 7.0.6, the tests started crashing. What was my surprise when after investigating it turned out that `destroy` doesn't work. In fact, everything is in the screenshots below:

<img width="1425" alt="Screenshot at Jul 04 18-29-06" src="https://github.com/rubysherpas/paranoia/assets/83755216/89b15e73-bf23-4751-aaf7-418911f79cab">
<img width="509" alt="Screenshot at Jul 04 18-31-09" src="https://github.com/rubysherpas/paranoia/assets/83755216/29f347d2-3560-416f-b9e5-123c6ee45d45">
<img width="1227" alt="Screenshot at Jul 04 19-07-03" src="https://github.com/rubysherpas/paranoia/assets/83755216/eb73deaf-d412-428c-8e11-446486e24e6b">

**Comment by dcrec1** [comment]
I have an issue related to this. In my case, for example `record.destroy` returns false, but the `deleted_at` column is updated.

**Comment by mathieujobin** [comment]
Thanks for reporting it. I don't know what would be causing it... 7.0.6 diff is pretty thin from 7.0.5

**Comment by Stashchenko** [comment]
> Thanks for reporting it. I don't know what would be causing it... 7.0.6 diff is pretty thin from 7.0.5

The same issue on the rails 7.0.7

**Comment by mathieujobin** [comment]
I'm sorry, I am unable to come up with a patch at the moment, but if someone is willing to fix this and open a pull request, I can review and release.

Thanks

**Comment by mjobin-mdsol** [comment]
can you try this https://github.com/rubysherpas/paranoia/pull/545 and let us know ?

**Comment by Stashchenko** [comment]
> can you try this #545 and let us know ?

Ok, will let you know about results

UPD: Nope, does not work :(

**Comment by VitaliSakolski** [comment]
> can you try this #545 and let us know ?

Just tried this solution - still doesn't work

**Comment by mathieujobin** [comment]
```
(byebug) subject
#<CostCenter id: 3, name: "Human Resources", account_id: 98, created_at: "2023-08-30 23:20:07.000000000 +0000", 
updated_at: "2023-08-30 23:20:07.000000000 +0000", deleted_at: nil>
(byebug) subject.destroy
#<CostCenter id: 3, name: "Human Resources", account_id: 98, created_at: "2023-08-30 23:20:07.000000000 +0000", 
updated_at: "2023-08-30 23:20:15.000000000 +0000", deleted_at: "2023-08-30 23:20:15.000000000 +0000">
(byebug) subject.reload
#<CostCenter id: 3, name: "Human Resources", account_id: 98, created_at: "2023-08-30 23:20:07.000000000 +0000", 
updated_at: "2023-08-30 23:20:15.000000000 +0000", deleted_at: "2023-08-30 23:20:15.000000000 +0000">

(byebug) CostCenter.where(id: 3)
#<ActiveRecord::Relation []>
(byebug) CostCenter.count 
2
(byebug) subject = CostCenter.where(id: 2).take 
#<CostCenter id: 2, name: "different name", account_id: 97, created_at: "2023-08-30 23:20:06.000000000 +0000", 
updated_at: "2023-08-30 23:20:06.000000000 +0000", deleted_at: nil>
(byebug) subject.destroy
#<CostCenter id: 2, name: "different name", account_id: 97, created_at: "2023-08-30 23:20:06.000000000 +0000", 
updated_at: "2023-08-30 23:21:35.000000000 +0000", deleted_at: "2023-08-30 23:21:35.000000000 +0000">
(byebug) CostCenter.count 
1
(byebug) CostCenter.find_by_sql('select * from cost_centers where deleted_at is not null')
[#<CostCenter id: 3, name: "Human Resources", account_id: 98, created_at: "2023-08-30 23:20:07.000000000 +0000", 

updated_at: "2023-08-30 23:20:15.000000000 +0000", deleted_at: "2023-08-30 23:20:15.000000000 +0000">, 
#<CostCenter id: 2, name: "different name", account_id: 97, created_at: "2023-08-30 23:20:06.000000000 +0000", 

updated_at: "2023-08-30 23:21:35.000000000 +0000", deleted_at: "2023-08-30 23:21:35.000000000 +0000">]
(byebug) 
```

what is wrong ?

**Comment by VitaliSakolski** [comment]
> 
> what is wrong ?

Where am I wrong?

### **Gemfile:**
<img width="795" alt="Screenshot at Aug 31 10-58-55" src="https://github.com/rubysherpas/paranoia/assets/83755216/588ef134-45f1-4c44-8616-6cdc62347026">

### **Result:**
<img width="539" alt="Screenshot_at_Aug_31_10-49-33(1)" src="https://github.com/rubysherpas/paranoia/assets/83755216/79306b04-f1d4-4a4b-a997-b2d07c10bbf6">

### **UPD:** 
Upon further investigation, the following issue was identified. Due to the specifics, we were using the `before_destroy` callback, which caused the above issue despite the patch. After replacing it with `after_destroy` everything started working as expected.

**Comment by mathieujobin** [comment]
I am also unsure what you use a fork version... Happy to hear you found the bug.

```
$ grep paranoia Gemfile*
Gemfile:gem 'paranoia'
Gemfile.lock:    paranoia (2.6.2)
Gemfile.lock:  paranoia
```
