### ISSUE TITLE
Rails main - no superclass method `each_counter_cached_associations'

### ISSUE THREAD

**Issue by JoeDupuis** [rubysherpas/paranoia#552]
[Rails main deleted `each_counter_cached_associations` ](https://github.com/rails/rails/pull/49866/files#diff-0441501ea93f2580c66bc58d845fcc2ad9dc5110cce249ce184c0b59483e253bL211-L215)(private api). 
The next release of Rails will break paranoia. 

I am getting this error when targeting rails main: 
`NoMethodError: super: no superclass method `each_counter_cached_associations'`

**Comment by mathieujobin** [comment]
Thanks for the heads up
