### ISSUE TITLE
Support for delete_all

### ISSUE THREAD

**Issue by mohammednasser-32** [rubysherpas/paranoia#565]
I was wondering if it is intentional that the gem does not support `delete_all` action, It is the reason behind [this](https://github.com/rubysherpas/paranoia/issues/538) bug since `has_many_through` uses `delete_all` to delete the related associations.

I was going to work on a PR to add it but I thought it would be better to double check first

Thank you

**Comment by mohammednasser-32** [comment]
@mathieujobin Hello :wave: can you please let me know if I can proceed with this? Thanks

**Comment by mathieujobin** [comment]
Yes please proceed.

If you could wrap your changes with a setting and make sure to cover up the feature with tests, that would be most appreciated 👍 

Thanks

**Comment by mohammednasser-32** [comment]
@mathieujobin Done :pray: [PR](https://github.com/rubysherpas/paranoia/pull/566)
