### ISSUE TITLE
Validates uniqueness of attribute(unique index)

### ISSUE THREAD

**Issue by mvoto** [rubysherpas/paranoia#63]
I have a problem here: an attribute that the model should validate its uniqueness, but only with non deleted records.

As this issue: https://github.com/radar/paranoia/issues/31
This would perfectly solve the problem, but this attribute has an unique index at database. So this solution didn't worked. And the customer does not allow me to change or remove this index.

Any ideas to solve this ?

**Comment by mvoto** [comment]
Well I guess that there is no way to handle this.
Actually we got it, convinced the customer to drop that index and recreate it without the unique true.

Closing this issue.

**Comment by radar** [comment]
Yes, database indexes won't acknowledge Ruby code.

**Comment by mvoto** [comment]
That's right, thanks !
