### ISSUE TITLE
destroy! implemented in Rails 4

### ISSUE THREAD

**Issue by garysweaver** [rubysherpas/paranoia#67]
Understand that paranoia is currently stated as a Rails 3 solution, but for future Rails 4 support:

https://github.com/rails/rails/blob/v4.0.0/activerecord/lib/active_record/persistence.rb#L169

Maybe force_\* methods would be better than bang methods? (e.g. force_destroy instead of destroy! and force_delete instead of delete!)

**Comment by radar** [comment]
@garysweaver There is a rails4 branch of this extension. Have you tried that yet? I like the idea of `force_` methods.

**Comment by MarkMurphy** [comment]
@radar why can't we just do destroy!(true) for forced deletes?

**Comment by radar** [comment]
@MarkMurphy Would that work? I'd like a patch for that if it does.

**Comment by radar** [comment]
@MarkMurphy ping

**Comment by MarkMurphy** [comment]
@radar Check out my fork of [paranoia](https://github.com/MarkMurphy/paranoia/tree/master) which could be made into a pull request.

**Comment by radar** [comment]
@MarkMurphy Please do submit a PR so I can look it over.

**Comment by jhawthorn** [comment]
Closing because we now have `really_destroy!`?
